<h2><?= __('module_user_group_add_service') . ' - ' . $this->userGroup->name ?></h2>

<div class="background-white pa-15">
<form <?= $this->request->getHTML() ?>>	
	<div class="col-xs-3 lh-35">
		  <label for="service"><?= __('module_user_group_service') ?></label>
	</div>
	<div class="col-xs-3">
		  <select class="form-control" id="service" name="id_service">
			<?php foreach ($this->services as $service) : ?>
			  <option value="<?= $service->id ?>"><?= $service->name ?></option>
			<?php endforeach; ?>
		  </select>
	</div>
	
	<div class="col-xs-3 lh-35">	
		  <label for="service_price"><?= __('module_user_group_service_price') ?></label>
	</div>
	<div class="col-xs-3">
		  <select class="form-control" id="service_price" name="id_service_price">
			<?php foreach ($this->servicePrices as $servicePrice) : ?>
				<?php if ( !empty($this->services) && $this->services[0]->id == $servicePrice->id_service ) : ?>
					<option value="<?= $servicePrice->id ?>"><?= $servicePrice->price . ' - ' . $servicePrice->time_interval ?></option>
				<?php endif;?>
			<?php endforeach; ?>
		  </select>
		
	</div>
	<div class="clearfix"></div>
	<div class="mt-15"></div>
	<div class="col-md-2 col-xs-2 lh-35"><?= __('module_service_from') ?></div>	
	<div class="col-xs-1">
		<select name="from_day">
			<?php foreach ($this->days as $day) : ?>
				  <option value="<?= $day ?>"
						  ><?= $day ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	<div class="col-xs-1">
		<select name="from_month">
			<?php foreach ($this->months as $month) : ?>
				  <option value="<?= $month ?>"
					<?= Helper_Default::getSelectedOrNull($this,'currentMonth',$month) ?>
						  ><?= $month ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	
	<div class="col-xs-2">
		<select name="from_year">
			<?php foreach ($this->years as $year) : ?>
				  <option value="<?= $year ?>"
					<?= Helper_Default::getSelectedOrNull($this,'currentYear',$year) ?>
						  ><?= $year ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	
	<div class="col-md-2 col-xs-2"><?= __('module_service_to') ?></div>
	<div class="col-xs-1">
		<select name="to_day">
			<?php foreach ($this->days as $day) : ?>
				  <option value="<?= $day ?>"
						  ><?= $day ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	<div class="col-xs-1">
		<select name="to_month">
			<?php foreach ($this->months as $month) : ?>
				  <option value="<?= $month ?>"
					<?= Helper_Default::getSelectedOrNull($this,'currentMonth',$month) ?>
						  ><?= $month ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	<div class="col-xs-2">
		<select name="to_year">
			<?php foreach ($this->years as $year) : ?>
				  <option value="<?= $year ?>"
					<?= Helper_Default::getSelectedOrNull($this,'nextYear',$year) ?>
						  ><?= $year ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	<div class="clearfix"></div>
	<div class="mt-15"></div>
	<div class="col-xs-9"></div>
	<div class="col-xs-3 text-right">
		<input type="submit" class="btn" value="<?= __('save') ?>">
	</div>
</form>
	<div class="clearfix"></div>
</div>
<script>
	var servicePricesPerService = jQuery.parseJSON('<?= $this->servicePricesPerService ?>');

	$(function() { 
		$("#service").change(function() { 
			var value = $(this).val();
			
			var html = '';
			var servicePrice;
			
			for ( servicePrice of servicePricesPerService[value] )
			{
				html += '<option value="' + servicePrice.id + '">' + servicePrice.price + ' - ' + servicePrice.time_interval + '</option>';
			}
			
			$("#service_price").html(html);
		});
	});
</script>