<div class="row-fluid marg-top-30">
		<div class="container text-center">
			<h2>Kontakt</h2>
			<div class="line-small"></div>
			<p>
				 V případě, že Vás naše služby zaujaly, nebo k nim máte otázky, můžete nás kontaktovat pomocí níže uvedeného formuláře.
			</p>

			<?= Art_Widget::render('contact', 'contactFormShort') ?>
			
			<div class="col-md-4 text-left">
				<h3 class="marg-bot-10 marg-top-20">Sídlo společnosti</h3>

				Třída generála Píky 13, 613 00 Brno - Černá pole<br>
				IČO: 02595354<br>
				DIČ: CZO2595354<br>
				e-mail: info@tbdevelopment.cz
				
				<h3 class="marg-top-20 marg-bot-10">Vedení společnosti</h3>
				<strong>Jednatel</strong><br>
				Ivo Burian<br>
				tel: +420 608 673 073<br>
				e-mail: burian@tbdevelopment.cz<br>
				<div class="marg-bot-10"></div>
				<strong>Jednatel</strong><br>
				Bc. Martin Tůma<br>
				tel: +420 720 316 767<br>
				e-mail: tuma@tbdevelopment.cz<br>
				<div class="marg-bot-10"></div>
				<strong>Jednatel a předseda spolku přátel při TBDI</strong><br>
				Mgr. Lukáš Špunar<br>
				tel: +420 776 575 179<br>
				e-mail: spunar@tbdevelopment.cz<br>
			</div>
		</div>
	</div>
	<div class="row-fluid marg-top-50">
		<div class="container">
			<h2>Kde nás najdete?</h2>
			<div class="line-small"></div>
		</div>
	</div>
	<iframe src="https://maps.google.com/maps?q=t%C5%99%C3%ADda%20Gener%C3%A1la%20P%C3%ADky%2013%2C%20%C4%8Cern%C3%A1%20Pole%2C%20613%2000%20Brno%2C%20%C4%8Cesko&t=&z=14&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" width="100%" height="450" style="border:0" allowfullscreen></iframe>