<div class="row-fluid marg-top-30">
		<div class="container text-center">
			<h2>O nás</h2>
			<div class="line-small"></div>
			<p class="text-justify">
				Jako firma jsme tu pro Vás od začátku roku 2014. K naší reklamní, developerké a vývojové činnosti jsme poté začátkem roku 2015 založili Spolek přátel při TBDI. V rámci tohoto partnerského spolku vytváříme síť společných známých, kteří se podílí na našich obchodních aktivitách. Spolek ovšem není pro každého. Je tvořen pouze úzkým okruhem přátel a známých. Členem se můžete stát pouze díky osobnímu doporučení některého z našich členů. Celá naše klubová strategie je postavena na tom, že spojujeme odběratele služby přímo s poskytovatelem. Tím dochází k nemalé úspoře financí, z důvodu vynechání několika článků distribuce. Jsme schopni našim členům stabilně zhodnotit finance v rozsahu 1,2% - 2,2% měsíčně a zároveň ušetřit desetitisíce ročně na věcech běžné spotřeby. Naši klienti a členové se na nás mohou vždy spolehnout. S partnerskými firmami pomáháme lidem postavit se na vlastní nohy.
			</p>
		</div>
	</div>
	<div class="row-fluid marg-top-50 marg-bot-50">
		<div class="container">
			<h2>Kdo jsme?</h2>
			<div class="line-small"></div>
			<p>
				TB DEVELOPMENT&INVESTMENT JE VYSOCE KVALIFIKOVANÁ A NA TRHU ZORIENTOVANÁ FIRMA ZABÝVAJÍCÍ SE REKLAMNÍ A DEVELOPERSKOU ČINNOSTÍ, VÝVOJEM WEBOVÝCH APLIKACÍ A AMBICIÓZNÍMI INVESTIČNÍMI ZÁMĚRY NA POLI OBCHODOVÁNÍ S NEMOVITOSTMI A BURZE.
			</p>
		</div>
	</div>