<div class="row-fluid marg-top-30">
	<div class="container text-center">
		<h2>Developerská činnost</h2>
		<div class="line-small"></div>
		<p class="text-justify">
			I navzdory výkyvům na trhu s nemovitostmi je developerská činnost, jež je naší hlavní prioritou, a které se do budoucna chceme věnovat na maximum, stále aktivním a atraktivním předmětem podnikání. Jedná se o multioborovou činnost, jejíž projekty patří do oblasti projektového financování. Developer je tedy zkušenou a spolehlivou osobou, která je investorem projektu, ale jejímž cílem není výsledný projekt vlastnit. Zájem výsledný projekt vlastnit má až finální investor, který však nechce podstupovat riziko výstavby, pod kterou rozumíme nejen realizaci stavby jako takové, ale všechny záležitosti kolem, např. různé možné změny územního plánu, vydávání stavebního povolení apod. Nákupem nemovitostí prostřednictvím developera se tedy finální investor snaží předcházet případným rizikům koupě.
</p>

		<p class="text-justify">
		Naše agentura TB development&investment operuje s celou řadou důvěryhodných developerů, kteří s nejvyšší mírou obezřetnosti provádějí veškeré dílčí činnosti developerského procesu, jako je vyhledávání nemovitosti, provádění důkladné studie realizace projektu, uzavírání developerských smluv, zajišťování vlastnických práv k nemovitosti, financování, potřebných povolení a odbytu projektu, výstavbu a finální převod projektu na investora.
</p>
		<p class="text-justify">
		Náš tým by chtěl v prvé řadě předestřít, že připravujeme projekty menších rodinných domů, dále také projekty rekonstrukce větších bytových a jiných nemovitostí, a že firma TB development&investment kooperuje s dalšími investory s dlouholetou praxí v oboru.
<p class="text-justify">
		 A opět nezapomínáme na připomínku exkluzivních služeb pro členy klubu, kteří apriorně získají podrobnější informace, a jenž budou mít možnost produktivní spolupráce na našich projektech.
</p>
	</div>
</div>