<div class="row-fluid marg-top-30">
	<div class="container text-center">
		<h2>Investiční záměry</h2>
		<div class="line-small"></div>
		<p class="text-justify">
			Co se týče investičních záměrů firmy TB development&investment, nabízí se Vám celá řada směrů, kterými se s námi máte možnost ubírat.
</p>

		<p class="text-justify">
		Hned zkraje bychom rádi načrtli investice do nemovitostí. Každému, alespoň částečně ekonomicky smýšlejícímu člověku neustále vyvstává otázka, jak svoje peníze uchovat a jak nejvýhodněji své úspory zvyšovat. Nemovitosti byly, jsou a vždy budou v tomhle ohledu populární způsob zajištění peněz, neboť se jedná o hmatatelnou investici, na katastrálním úřadě, tedy státní správou registrovaný produkt a ať už na trhu s nemovitostmi docházelo k různým výkyvům, například vlivem finanční krize, dříve nebo později se vždy cena nemovitosti vrátila na cenu nákupní, většinou ovšem na cenu vyšší. Nemáte se tedy čeho obávat, naši investoři sledují Váš profit, dohlížejí na klíčové faktory při investici do nemovitostí, jako je lokalita, roční výnos z nemovitosti, obnovení cenového růstu na trhu, výhody a nevýhody při nákupu rezidenční či komerční nemovitosti, různá kvalitativní kritéria apod.
</p>
		<p class="text-justify">
		Dále bychom Vám rádi představili naše investice na kapitálových trzích formou arbitráží s měnovými páry. Ale nechceme teoretizovat, v praxi se jedná o využití cenového rozdílu mezi dvěma nebo více trhy, kdy zisk sestává právě z rozdílu mezi tržními cenami. Simplicitně řečeno to znamená nakoupit nízko a prodat vysoko. Při pohlídání si transakčních nákladů můžeme v podstatě mluvit o bezrizikovém zisku. Formou arbitráže se obchoduje s finančními nástroji, jako jsou dluhopisy, akcie, deriváty, komodity a měny. Současně je ale naším úkolem zdůraznit, že se nejedná o forex!
<p class="text-justify">
		Naše investice budou směřovat i do projektů třetích stran. Taktéž zpracováváme zobrazení aktuálních investic. 
</p>
<p class="text-justify">
	Podrobnější informace a další detaily týkající se aktuálních investičních záměrů jsou k dispozici členům našeho klubu.

</p>
	</div>
</div>