<div class="row-fluid marg-top-30">
	<div class="container text-center">
		<h2>Vývoj webových aplikací</h2>
		<div class="line-small"></div>
		<p class="text-justify">
			V důsledku decentralizace informační a mediální distribuce a stále větší komercializace internetu bychom rádi avizovali, že jedním z připravovaných projektů naší firmy je i expanze do oblasti webových aplikací. Naším cílem je vytvářet dynamické webové stránky, s tím souvisí rozvoj právě zmiňovaných internetových aplikací, elektronických obchodů a jejich případnou propojenost se sociálními sítěmi. Příkladem dramatické transformace v oblasti obchodu a komunikace v rámci developmentu webových aplikací jsou e-shops nebo-li internetové obchody, možnost jakým mohou spotřebitelé z pohodlí domova provádět on-line nákupy zboží a služeb.
</p>

		<p class="text-justify">
		Naším cílem však není dané produkty přímo prodávat, pouze je zprostředkovaně nabízet na námi vyvíjené webové stránce v rámci oboustranně výhodného partnerského marketingu. Způsob nákupu zůstává pro každého zákazníka stále stejně neuvěřitelně jednoduchý a efektivní. Jako klient máte k dispozici nepřeberné množství výhodných nabídek a akcí na jednom portálu, ať už toužíte po ideální prázdninové dovolené, hledáte designové spotřebiče pro domácnost, špičkově výkonnou elektroniku, inspiraci v módě či se Vaše zájmy týkají sportovního vyžití. Zkrátka a dobře, sortiment pro celou rodinu na jednom místě! Také v další fázi nákupu je zaručen hladký průběh, kdy se daná, námi zaručená, společnost telefonicky či e-mailem spojí s klientem a ověří objednávku. Veškeré nakupování se uskuteční tedy rychle a bezproblémově.
</p>
		
		<p class="text-justify">
		A protože firmě TB development&investment nechybí inovativnost a nápad, naším dalším plánem na to-do-listu je doplnění k našim stránkám mobilní aplikace do všech typů smartphonů, aby on-line nakupování bylo pro každého zákazníka ještě více komfortní a kdekoli přístupné.
</p>
		<p class="text-justify">
		 Rádi bychom Vás také upozornili, že členové klubu budou mít z používání našich webových aplikací k dispozici širokou škálu skvělých benefitů.
</p>
	</div>
</div>