<div class="row-fluid marg-top-30">
	<div class="container text-center">
		<h2>Reklamní činnost</h2>
		<div class="line-small"></div>
		<p class="text-justify">
			V dnešní době rozvoje digitálního marketingu nabývá tzv. emailing na stále vyšší účinnosti. V nejširším slova smyslu se jedná o rozesílání aktuálnímu či potenciálnímu zákazníkovi komerční elektronickou poštu, jejímž obsahem může být inzerát či obecněji reklama, nabídka podnikání, nákupu, prodeje či daru. E-mailový marketing z dlouhodobého hlediska také umožňuje tzv. feedback, nebo-li zpětnou vazbu. Marketér má tedy možnost za velice nízké náklady testovat a vyhodnocovat úspěšnost své obchodní činnosti, získávat podněty, námitky, připomínky, pozitivní i negativní ohlasy a zákaznické reakce. Vyšší míra odezvy a s tím spojená i větší návratnost investic je jistě jednou z nejzásadnějších výhod.
</p>

		<p class="text-justify">
		Další významné plus spočívá v přesném zacílení na určitý segment trhu, tedy okruh zákazníků majících o určité nabídky a témata zájem. Firma tedy nemusí vynakládat zbytečné usilí na zasílání reklam, které pro daného klienta nejsou zajímavé. Naopak, zákazník obdrží specifické informace, které jsou pro něj nejen žádoucí, ale z jeho strany přímo očekávané. Pointa tedy spočívá v oboustranné výhodnosti.
</p>
		<p class="text-justify">
		V neposlední řadě je třeba zdůraznit, jakým výrazným způsobem e-mail marketing spěje k budování loajality, důvěry i povědomí o značce jako takové. Je to způsob jak získávat nové zákazníky a uchovávat a pečovat o ty staré.
</p>
		<p class="text-justify">
		Společnost TB development&investment má navíc ke všem těmto potřebám k dispozici objemnou databázi zákazníků, tedy přesný seznam e-mailových adres z našeho úspěšného projektu masmail.cz. To vše s příslibem ustavičného vývoje, zlepšování poskytování služeb a skvělých cen. Naše zkušenosti jsou navíc podpořeny i spoluprací s neméně kvalifikovanou partnerskou marketingovou firmou neuronmedia.eu, jež se zaměřuje na hospodářskou soutěž mezi podnikateli prostřednictvím nejrůznějších sociálních sítí a mediálních nástrojů.
</p>
		<p class="text-justify">
		Na závěr k naší reklamní činnosti nezapomínáme zdůraznit výhody, které čekají na členy našeho klubu. Namátkou lze zmínit nižší ceny či vícestranně výhodný bártrův obchod při střetu nabídky s poptávkou, tedy Vaše reklama reciprocitně za služby jiným členům bez vynaložení finančních nákladů.
</p>
	</div>
</div>