<?php $prefix = Helper_Default::getPropertyOrNull($this->bankAccount,'prefix'); ?>

<h2 class="text-center"><?= __('module_users_edit_bank_account') ?></h2>
<div class="line-2colors"></div>

<div class="background-white pt-20 pb-20 pl-20 pr-20 horizontal-center table75">	
	<?php 
		foreach ($this->bankAccounts as $value) :
			$prefix = Helper_Default::getPropertyOrNull($value, 'prefix');
	?>
	<div class="row">
		<div class="col-md-2">
			<input name="prefix" type="text" value="<?= $prefix; ?>" class="form-control" disabled>
		</div>
		<div class="col-md-4">
			<div style="position: absolute; margin-left: -17px; margin-top: 5px;">-</div> <input name="basic" type="text" value="<?= Helper_Default::getPropertyOrNull($value, 'basic') ?>" class="form-control" placeholder="<?= __('bank_account_basic') ?>" disabled>
		</div>
		<div class="col-md-2">
			<div style="position: absolute; margin-left: -17px; margin-top: 5px;">/</div>
			<input name="bank_code" type="text" value="<?= Helper_Default::getPropertyOrNull($value, 'bank_code') ?>" class="form-control" placeholder="<?= __('bank_account_bank_code') ?>" disabled>
		</div>
		<div class="col-md-3">
			<input name="note" type="text" value="<?= Helper_Default::getPropertyOrNull($value, 'note') ?>" class="form-control" disabled>
		</div>	
		<div class="col-md-1 row-actions">
			<a href="javascript:;" <?= $this->requestRemove->getHTML(array('id' => $value->id)) ?>><i class="fa fa-trash-o"></i></a>
		</div>
	</div>
	<?php 
		endforeach;
	?>
</div>


<form <?= $this->request->getHTML() ?>>
	<div class="background-white pt-20 pb-20 pl-20 pr-20 horizontal-center table75">
		<div class="row">
			<div class="col-md-2">
				<input name="prefix" type="text" class="form-control" placeholder="<?= __('bank_account_prefix') ?>">
			</div>
			<div class="col-md-4">
				<div style="position: absolute; margin-left: -17px; margin-top: 5px;">-</div> <input name="basic" type="text" autofocus="true"class="form-control" placeholder="<?= __('bank_account_basic') ?>">
			</div>
			<div class="col-md-2">
				<div style="position: absolute; margin-left: -17px; margin-top: 5px;">/</div>
				<input name="bank_code" type="text" class="form-control" placeholder="<?= __('bank_account_bank_code') ?>">
			</div>
			<div class="col-md-3">
				<input name="note" type="text" class="form-control" placeholder="<?= __('note') ?>">
			</div>	
			<div class="col-md-1 row-actions">
				
			</div>
		</div>
	</div>
	<div class="save-view-buttons mt-15">
		<input type="submit" class="btn btn-info" value="<?= __('add') ?>">
	</div>
</form>