<h2><?= __('module_users_change_password_header') ?></h2>

<form <?= $this->request->getHTML() ?>>
	<table class="table50 horizontal-center background-white">
		<tr>
			<td class="text-right pr-10">
				<?= __('module_users_change_password_actual') ?>
			</td>
			<td class="pl-10">
				<input name="passwd_old" type="password" class="form-control" placeholder="<?= __('module_users_change_password_actual') ?>">
			</td>
		</tr>
		<tr>
			<td class="text-right pr-10">
				<?= __('module_users_change_password_new') ?>
			</td>
			<td class="pl-10">
				<input name="passwd_new1" type="password" class="form-control" placeholder="<?= __('module_users_change_password_new') ?>">
			</td>
		</tr>
		<tr>
			<td class="text-right pr-10">
				<?= __('module_users_change_password_new_again') ?>
			</td>
			<td class="pl-10">
		<input name="passwd_new2" type="password" class="form-control" placeholder="<?= __('module_users_change_password_new_again') ?>">
			</td>
		</tr>
	<tr>
		<td class="text-right" colspan="2">
			<input type="submit" class="btn btn-info" value="<?= __('module_users_change_password_send') ?>">
		</td>
</tr>
	
	</table>
</form>