<h2 class="text-center"><?= __('module_users_change_password_header') ?></h2>

<form <?= $this->request->getHTML() ?>>
	<table class="table75 horizontal-center background-white">
		<colgroup>
			<col class="w30">
		</colgroup>
		<tr>
			<td class="text-right pr-10">
				<?= __('module_users_change_password_actual') ?>
			</td>
			<td class="pl-10">
				<input name="passwd_old" type="password" class="form-control" autofocus="true" placeholder="<?= __('module_users_change_password_actual') ?>">
			</td>
		</tr>
		<tr>
			<td class="text-right pr-10">
				<?= __('module_users_change_password_new') ?>
			</td>
			<td class="pl-10">
				<input name="passwd_new1" type="password" class="form-control" placeholder="<?= __('module_users_change_password_new') ?>">
			</td>
		</tr>
		<tr>
			<td class="text-right pr-10">
				<?= __('module_users_change_password_new_again') ?>
			</td>
			<td class="pl-10">
				<input name="passwd_new2" type="password" class="form-control" placeholder="<?= __('module_users_change_password_new_again') ?>">
			</td>
		</tr>
	</table>

	<div class="save-view-buttons mt-15">
		<input type="submit" class="btn btn-info" value="<?= __('module_users_change_password_send') ?>">
	</div>
</form>