
<div class="col-xs-4 np text-center">
	<?php if ( !$this->isManager ) : ?>
		<?= null//__('account-balance') ?> 
		<?= __('paid-until') ?>
		<?= $this->membership_to ?>
	<?php endif;?>
</div>
<div class="col-xs-2 np text-center none">
	<button class="small-ico button-mail"  style="display: none;"><i class="fa fa-envelope fa-2x"><span class="badge">3</span></i></button>
</div>
<div class="col-xs-5">
	<?php if ( $this->isManager ) : ?>
		<?= __('manager') ?>:
	<?php endif;?>
		
	<?php if ( $this->isCompany ) : ?>
		<?= Helper_TBDev::getCompanyNameForUser($this->user) ?>
	<?php else : ?>
		<?= $this->user->fullname ?>
	<?php endif;?>
	
	<span class="text-small">(Členské číslo <?= $this->user->user_number ?>)</span>
		
	<?php if ( !$this->isManager ) : ?>
		<?= 'Váš konzultant' ?>: <a href="<?= $this->p_managerDetail?>"><?= $this->manager->fullname ?></a> 
	<?php endif;?>
		
</div>
<div class="col-xs-2 np text-right">
	<?= Art_Widget::render('login', 'embedd', array('size'=>'small')); ?>
</div>

