<div class="membership-details">
	<div class="paid-until">
		<?php if (!$this->isManager) : ?>
			<?= __('paid-until') ?> <?= $this->membership_to ?>
		<?php endif; ?>
	</div>

	<div class="login-details">		
		<?php
		echo sprintf("%s %s", 
			__('logged-as'),
			$this->isCompany ? Helper_TBDev::getCompanyNameForUser($this->user) : $this->user->fullname
		);

		if ($this->isManager) {
			echo sprintf(" %s %s", __('membership-with-rights'), __('manager'));
		}

		
		echo sprintf(", %s <b>%s</b>",
			__('member-id-is'),
			$this->user->user_number
		);

		if (!$this->isManager) {
			echo sprintf(', %s: <a href="%s"><b>%s</b></a>',
					__('your-consultant-is'),
					$this->p_managerDetail,
					$this->manager->fullname 
			);
		}
		?>		
	</div>
</div>