
<?php if ( !$this->isManager ) : ?>
	<div class="col-xs-4">	
		<?= null//__('account-balance') ?> 
		<?= __('paid-until') ?>
		<?= $this->membership_to ?>
	</div>	
<?php endif;?>

<div class="col-xs-5 role">
	<span>
		<?php if ( $this->isManager ) : ?>
			<?= __('manager') ?>:
		<?php endif;?>
			
		<?php if ( $this->isCompany ) : ?>
			<?= Helper_TBDev::getCompanyNameForUser($this->user) ?>
		<?php else : ?>
			<?= $this->user->fullname ?>
		<?php endif;?>
	</span>
	
	<?php if ( !$this->isManager ) : ?>
		<?= 'Váš konzultant' ?>: <a href="<?= $this->p_managerDetail?>"><?= $this->manager->fullname ?></a> 
	<?php endif;?>	

	<span class="text-small"><small>Členské číslo <span><?= $this->user->user_number ?></span></small></span>
</div>