<?php if (!empty($this->userInvitedByFullname)) : ?>
	<h3><?= sprintf('%s: <span>%s</span>', __('module_users_inviteted_by'), $this->userInvitedByFullname) ?></h3>
<?php endif; ?>  
	

<div class="background-white introduction-text">
	<p class="text-justify">
		<strong>K jakému účelu kód slouží?</strong>
	</p>
	<p>
		Díky Vašemu pozvánkovému kódu se mohou do klubu zaregistrovat Vaši přátelé či rodina. Jelikož náš klub není úplně veřejným místem, rádi bychom si udrželi přehled o tom, odkud se berou noví členové a proč se k nám registrují. Není to tak, že bychom někomu chtěli bránit stát ses členem, ale nechceme, aby se k nám registrovali lidé například jen tak pro zábavu.
	</p>
	<p class="text-justify">
		Pozvánkový kód můžete poskytnout přímo jako webový odkaz pro registraci, anebo jako samostatný kód, který se při registraci vyplní do příslušného rámečku.
	</p>
</div>

<?php if (!empty($this->joinedUsers)) : ?>
<hr class="line-2colors">

<div class="row-fluid">
	<table class="table-default colored-rows">
		<tr>
			<th colspan="2"><?= __('module_users_invite_code_users_joined') ?></th>
		</tr>
		<?php foreach ($this->joinedUsers as $joinedUser) : ?>
		<tr>
			<td><?= $joinedUser->fullname ?></td>
			<td><?= $joinedUser->invCode ?></td>
		</tr>
		<?php endforeach; ?>		
	</table>
</div>
<?php endif; ?>

<hr class="line-2colors">
	
<div class="row-fluid mt-20">
	<h3>Vytvořte si vlastní unikátní pozvánkový kód.</h3>
	<form class="generate-unique-code" <?= $this->add_invite_code_request->getHTML() ?>>
		<input type="submit" class="btn btn-info mr-20" value="<?= __('module_users_generate_new_code') ?>">
		<input name="note" type="text" class="form-control" placeholder="<?= __('module_users_inv_code_note') ?>">
	</form>
</div>

<hr class="line-2colors">
		
<?php if (!empty($this->codes)) : ?>	
<div class="row-fluid">
	<h3>Vytvořené pozvánkové kódy:</h3>
	<table class="table-default">
		<colgroup>
			<col class="w15">
			<col class="w45">
			<col class="w40">
		</colgroup>
		<tr>
			<th>Kód</th>
			<th>Odkaz</th>
			<th>Poznámka</th>
		</tr>
		<?php foreach ($this->codes as $value) : ?>
		<tr>
			<td><?= substr($value->URL, 38, 13); ?></td>
			<td><?= $value->URL ?></td> 
			<td><?= $value->note ?></td>
		</tr>
		<?php endforeach; ?>
	</table>
</div>
<?php endif; ?>