<div class="col-xs-6">
		<div class="col-xs-12"><h3><?= __('module_users_manager_info') ?></h3></div>
		<div class="col-xs-4"><?= __('fullname') ?></div>
		<div class="col-xs-8">
			<?= $this->manager->fullname ?>
		</div>

		<div class="clearfix"></div>
		<div class="col-xs-4"><?= __('phone_number') ?></div>
		<div class="col-xs-8">
			<?= $this->phone ?>
		</div>
		<div class="clearfix"></div>
		<div class="col-xs-4"><?= __('email') ?></div>
		<div class="col-xs-8">
			<?= $this->manager->email ?>
		</div>
</div>