<h2><?= __('module_note_edit_header') ?></h2>

<form <?= $this->request->getHTML() ?> class="form">
	<div class="note-edit">
		<label for="note"><?= __('module_note_body') ?></label>
		<input id="note" name="body" autofocus type="text" value="<?= $this->note->body ?>">
	</div>
	<div class="save-view-buttons mt-15">
		<input type="hidden" value="<?= $this->email ?>">
		<input type="submit" class="button" value="<?= __('save') ?>">
	</div>
</form>