<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_article_articles') ?></h2>
	</div>
	<div class="col-sm-6 action-submenu page-actions">
		<?php /*
		<div class="action-new tile">
			<button <?= $this->unpublish_request->getHTML() ?>>
				<i class="fa fa-eye-slash fa-2x"></i>
				<?= __('unpublish') ?>
			</button>
		</div>
		<div class="action-new tile">
			<button <?= $this->publish_request->getHTML() ?>>
				<i class="fa fa-eye fa-2x"></i>
				<?= __('publish') ?>
			</button>
		</div>
		<div class="action-new tile">
			<button <?= $this->delete_selected_request->getHTML() ?>>
				<i class="fa fa-trash-o fa-2x"></i>
				<?= __('delete') ?>
			</button>
		</div> */ ?>
		<div class="action-new tile">
			<a href="/<?= Art_Router::getLayer() ?>/article/new">
				<?= icon('add'); ?>
				<?= __('module_article_add') ?>
			</a>
		</div>
	</div>
</div>

<table class="table-default list-articles">
	<colgroup>
		<col class="f60">
	</colgroup>
	<tr>
		<th></th>
		<!-- <th class="text-center"><input type="checkbox" onclick="toggleCheck(this,'.module_article_index .cb-article-list')"></th> -->
		<th><?= __('module_article_title') ?></th>
		<th><?= __('module_article_perex') ?></th>
	</tr>
	<?php foreach($this->articles as $article): ?>
		<?php $href = '/' . Art_Router::getLayer() . '/article/edit/' . $article->id; ?>
		<tr>
			<td>
				<div class="inline-sort">
					<?php if($this->sort_buttons[$article->id][Art_Model::SORT_UP]): ?>
						<button <?= $this->move_up_request->getHTML(array('id' => $article->id)) ?> class="arrow-up" title="<?= __('move_up') ?>"><i class="fa fa-arrow-up"></i></button>
					<?php endif; ?>
					<?php if($this->sort_buttons[$article->id][Art_Model::SORT_DOWN]): ?>
						<button <?= $this->move_down_request->getHTML(array('id' => $article->id)) ?> class="arrow-down" title="<?= __('move_down') ?>"><i class="fa fa-arrow-down"></i></button>
					<?php endif; ?>
				</div>
			</td>
			<!-- <td class="xsmall-td text-center"><input type="checkbox" name="article_<?= $article->id ?>" class="cb-article-list"></td> -->
			<td>
				<a href="<?= $href ?>"><?= $article->title ?></a>
			</td>
			<td>
				<a href="<?= $href ?>"><?= $article->perex ?></a>
				<div class="inline-actions">
					<button <?= $this->delete_single_request->getHTML(array('id' => $article->id, 'name' => $article->title)) ?> title="<?= __('delete') ?>"><i class="fa fa-trash-o"></i></button>
				</div>
			</td>
		</tr>
	<?php endforeach; ?>
</table>