<h2><?= __('module_article_new_article') ?></h2>
<form <?= $this->request->getHTML() ?>>
	<table class="table-default articles">
		<tr>
			<td class="xsmall-td text-right">
				Titulek
			</td>
			<td>
				<input type="text" name="title" placeholder="<?= __('module_article_title') ?>" value="">
			</td>
			<td class="xsmall-td text-right">
				URL
			</td>
			<td colspan="2">
				<input type="text" name="url_name" placeholder="<?= __('module_article_url') ?>" value="">
			</td>
		</tr>
		<tr>
			<td class="text-right">
				Perex
			</td>
			<td colspan="5">
				<textarea placeholder="<?= __('module_article_perex') ?>" name="perex" rows="3"></textarea>
				
			</td>
		</tr>
		<tr>
			<td colspan="6">
				<textarea class="ckeditor" name="content" placeholder="<?= __('module_article_content') ?>"></textarea>
			</td>
		</tr>
		<tr>
			<td colspan="6">
				META nastavení
			</td>
		</tr>
		<tr>
			<td colspan="6">
				<input type="text" name="meta_title" placeholder="<?= __('module_article_meta_title') ?>" value="">
			</td>
		</tr>
		<tr>
			<td colspan="6">
				<input type="text" name="meta_keywords" placeholder="<?= __('module_article_meta_keywords') ?>" value="">
			</td>
		</tr>
		<tr>
			<td colspan="6">
				<input type="text" name="meta_description" placeholder="<?= __('module_article_meta_description') ?>" value="">
			</td>
		</tr>
	</table>
	<div class="text-center">
		<input type="submit" value="<?= __('save') ?>" class="button-save">
	</div>
</form>

