
<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_payments_header') ?></h2>
	</div>
	<div class="col-sm-6 action-submenu">
		<div class="action-new">
			<a href="/<?= Art_Router::getLayer() ?>/payments/new">
			<i class="fa fa-plus fa-2x"></i>
			<?= __('add') ?></a>
		</div>
	</div>
</div>

<div class="filter-container">
	<?= Art_Widget::render('filter', 'embeddPayment') ?>
</div>

<table class="table-default">
	<colgroup>
		<col class="w25">
		<col class="w25">
		<col class="w10">
		<col class="w15">
		<col class="w20">
	</colgroup>
	<tr>
		<th><?= __('module_payments_user') ?></th>
		<th><?= __('module_payments_payer') ?></th>
		<th><?= __('module_payments_service') ?></th>
		<th><?= __('module_payments_value') ?></th>
		<th><?= __('module_payments_date') ?></th>
	</tr>
	<?php foreach ($this->payments as $key => $payment) : /* @var $payment Service_Payment */ ?>
	<tr>
		<!-- <td>
			<?= $payment->user_number ?>
		</td> -->
		<td>
			<span class="user-name"><?= $payment->user_fullname ?></span>
		</td>
		<td>
			<span class="company-name"><?= $payment->user_paid_by_fullname ?></span>
		</td>
		<td>
			<?= $payment->service_name ?>
		</td>
		<td>
			<?= money_format('%n', $payment->value) ?>
		</td>
		<td>
			<?= nice_date($payment->date) ?>
			<?php if ($this->lastPayments[$payment->user_id][$payment->service_id] == $key ) : ?>
			<div class="inline-actions">
				<button <?= $this->delete_single_request->getHTML(array('id'=>$payment->id)) ?> title="<?= __('delete') ?>"><i class="fa fa-trash-o"></i></button>
			</div>
			<?php endif; ?>
		</td>
	</tr>
	<?php endforeach; ?>
</table>

<script>
$(document).ready(() => {
	$('.chosen-select').chosen({
		max_selected_options: -1
	});
	$('.chosen-container').removeClass('chosen-disabled');

	function filterRows (cellSelector) {
		let value = event.currentTarget.value;

		let tr = $("table.table-default").find("tr");

		tr.each((i, row) => $(row).removeClass('hide'));
		tr.each((index, row) => {
			if (index === 0) return;
			let name = $(row).find(`td .${cellSelector}`).text();
			if (name.toLowerCase().indexOf(value) === -1)
				$(row).addClass('hide');
		});
	}

	$("#user-name").keyup((event) => {
		filterRows('user-name');
	});
	$("#company-name").keyup((event) => {
		filterRows('company-name');
	});
});
</script>