<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_payments_header') ?></h2>
	</div>
	<div class="col-sm-6 page-actions">
		<div class="action-new tile">
			<a href="/<?= Art_Router::getLayer() ?>/payments/new">
			<?= icon('add'); ?>
			<?= __('add') ?></a>
		</div>
	</div>
</div>

<div class="table-filter collapsed">
	<?= Art_Widget::render('filter', 'embeddPayment') ?>
	<div class="filter-handle">
		<?= __('module_filter_quick_header') ?>
	</div>
</div>

<table class="table-default table-list" data-sortable>
	<colgroup>
		<col class="w15">
		<col class="w60">
		<col class="w20">
	</colgroup>
	<thead>
		<tr>
			<th data-sorted="true" data-sorted-direction="descending">
				<span><?= __('module_payments_date') ?></span>
			</th>
			<th data-sortable="false">
				<span><?= __('module_payments_payer') ?></span>
			</th>
			<th data-sortable="false">
				<span><?= __('module_payments_value') ?></span>
			</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->payments as $key => $payment) : ?>
		<tr>
			<td data-value="<?= $payment->date ?>">
				<?= nice_date($payment->date) ?>
			</td>
			<td>
				<b class="payer-name"><?= $payment->user_paid_by_fullname; ?></b>
				<?php if ($payment->user_fullname !== $payment->user_paid_by_fullname) : ?>
					<?= __('module_payments_paid_instead') ?>
					<span class="user-name"><?= $payment->user_fullname; ?></span>
				<?php endif; ?>
				<?= __('module_payments_paid_for') ?>
				<b><?= $payment->service_name ?></b>
			</td>
			<td>
				<?= money_format('%n', $payment->value) ?>
				<?php if ($this->lastPayments[$payment->user_id][$payment->service_id] == $key ) : ?>
				<div class="inline-actions">
					<button <?= $this->delete_single_request->getHTML(array('id'=>$payment->id)) ?> title="<?= __('delete') ?>"><i class="fa fa-trash-o"></i></button>
				</div>
				<?php endif; ?>
			</td>		
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<script>
$(document).ready(() => {
	function filterRows (cellSelector) {
		let value = event.currentTarget.value;

		let tr = $("table.table-default").find("tr");

		tr.each((i, row) => $(row).removeClass('hide'));
		tr.each((index, row) => {
			if (index === 0) return;
			let name = $(row).find(`td .${cellSelector}`).text();
			if (name.toLowerCase().indexOf(value) === -1)
				$(row).addClass('hide');
		});
	}

	$("#payer-name").keyup((event) => {
		filterRows('payer-name');
	});

	$('.table-filter .filter-handle').click((event) => {
		event.preventDefault();
		event.stopPropagation();

		$(event.currentTarget).parent().toggleClass('collapsed');
	});
});
</script>