	
<h2><?= __('module_investment_header') ?> - Detail</h2>
<?php if (!empty($this->dataset)) : ?>
	<?php foreach ($this->dataset as $key => $investment) : /* @var $value Service_Investment_Value[] */ ?>
		<table class="table-default">
			<caption>
				<b><?= Helper_Default::getCzechMonthName($this->month).' '.$this->year.' - '.$this->investments[$key]->target ?></b>
				<button title="Upravit"><a href="/<?= Art_Router::getLayer() ?>/investment/editinvestment/<?= $key ?>"><i class="fa fa-pencil"></i></a></button>
				<button <?= $this->delete_request->getHTML(array('id'=>$key)) ?> title="<?= __('delete') ?>"><i class="fa fa-trash-o"></i></button>
				<?php if ( 0 == $this->investments[$key]->visible ) : ?>
					<button <?= $this->publish_request->getHTML(array('id'=>$key)) ?> title="<?= __('publish') ?>"><i class="fa fa-eye"></i></button>
				<?php else : ?>
					<button <?= $this->unpublish_request->getHTML(array('id'=>$key)) ?> title="<?= __('unpublish') ?>"><i class="fa fa-eye-slash"></i></button>
				<?php endif; ?>
			</caption>
			<colgroup>
				<col class="w30">
				<col class="w15">
				<col class="w10">
				<col class="w15">
				<col class="w15">
				<col class="w15">
				<col class="f30">
			</colgroup>
			<tr>
				<th><?= __('fullname') ?></th>
				<th class="text-right"><?= __('module_investment_invested') ?></th>
				<th><?= __('module_investment_interest') ?></th>
				<th><?= __('module_investment_gain') ?></th>
				<th><?= __('module_investment_commision') ?></th>
				<th><?= __('module_investment_payment_date') ?></th>
				<th></th>
			</tr>
			<?php 
				foreach ($investment as $value) : /* @var $value Service_Investment_Value */ 
			?>
				<tr>
					<td>
						<?= $value->getUser()->fullname ?>
					</td>
					<td class="text-right">
						<?= money_format('%n', $value->invested) ?>
					</td>
					<td>
						<?= $value->interest ?>%
					</td>
					<td>
						<?= money_format('%n', ($value->invested * $value->interest / 100)) ?></td>
					<td>
						<?= money_format('%n', $value->commission) ?>
					</td>
					<td>
						<?= nice_date($value->payment_date) ?>
					</td>
					<td>
						<a href="javascript:;" data-toggle="tooltip" title="<?= $value->note ?>"><i class="fa <?= !empty($value->note) ? 'fa-comment' : 'fa-comment-o' ?> edit"></i></a>
					</td>
				</tr>
			<?php endforeach; ?>
		</table>
	<?php endforeach; ?>
<?php else: ?>
<h4>No investments defined yet.</h4>
<?php endif; ?>
<script>
$(document).ready(() => {	
	$('[data-toggle="tooltip"]').tooltip();
});
</script>