<h2><?= __('module_investment_edit_deposit') ?></h2>
<div class="background-white pa-15">
	<form <?= $this->request->getHTML() ?>>
		<div class="col-xs-12">
			<div class="col-xs-2"><?= __('module_payments_payer') ?></div>		
			<div class="col-xs-4">
				<?= $this->deposit->getUser()->fullname ?>
			</div>	
			<div class="col-xs-2"><?= __('module_investment_deposit_value') ?></div>
			<div class="col-xs-4">
				<?= $this->deposit->value ?>
			</div>
			
		</div>	
		<div class="col-xs-12 mt-15">
			
			<div class="col-xs-2 lh-35">Datum vkladu</div>
			<div class="col-xs-4 lh-35">
				<?= nice_date($this->deposit->date) ?>
			</div>

			<div class="col-xs-2 lh-35">Datum expirace</div>
			<div class="col-xs-4">
				<input name="expiry_date" type="text" class="form-control" placeholder="00.00.0000"
					   value="<?= nice_date($this->deposit->expiry_date) ?>">
			</div>

		</div>
		<div class="col-xs-12 mt-15">

			<div class="col-xs-2 lh-35">Poznámka</div>
			<div class="col-xs-4">
				<input name="note" type="text" class="form-control"
					   value="<?= $this->deposit->note ?>">
			</div>

			<div class="col-xs-3"></div>
			<div class="text-center col-xs-3">
				<input type="submit" value="<?= __('save') ?>" class="btn">
			</div>

		</div>
		<div class="clearfix"></div>
	</form>
</div>

<script>
$('.invested,.interest').focusout(
			function(){
				var interest = $(this).val();
				var invested = $(this).parent().parent().find('.invested-td').find('.invested').val();
				$(this).parent().parent().find('.gain-td').find('.gain').val(interest*invested/100);
			}
			);
	</script>