<h2>Editace Investicí</h2>

<form <?= $this->request->getHTML() ?>>

	<input type="hidden" name="month" value="<?= $this->month ?>">
	<input type="hidden" name="year" value="<?= $this->year ?>">
	<input type="hidden" name="investmentId" value="<?= $this->investmentId ?>">
	
	<input type="text" name="target" value="<?= $this->target ?>">
	
	<table class="table-default variable">
		<caption><b><?= Helper_Default::getCzechMonthName($this->month) ?> <?= $this->year ?> - <?= $this->target ?></b></caption>
		<col class="f30"/>
		<col class="w20"/>
		<tr>
			<th><input type="checkbox" onclick="toggleCheck(this,'.module_investment_editinvestment .cb-investment-list')" class="cb-investment-head"></th>
			<th><?= __('fullname') ?></th>
			<th><?= __('module_investment_invested') ?></th>
			<th><?= __('module_investment_interest') ?></th>
			<th><?= __('module_investment_gain') ?></th>
			<th><?= __('module_investment_commision') ?></th>
			<th><?= __('module_investment_payment_date') ?></th>
			<th><?= __('note') ?></th>
		</tr>
		<?php 
			foreach( $this->investmentValues as $i => $value ) : /* @var $value Service_Investment_Value */
				$tabindex = ++$i;
				$user = $value->getUser();
				$userId = $user->id;
				$invested = $value->invested;
				$interest = $value->interest;
		?>
			<tr>
				<td class="xsmall-td">
					<input type="checkbox" name="investment-<?= $userId ?>" tabindex="-1" class="cb-investment-list">
				</td>
				<td><?= Art_Filter::cutString($user->fullname, 40) ?></td>
				<td class="invested-td">
					<input type="text" class="invested" name="invested-<?= $userId ?>" tabindex="-1" placeholder="<?= __('module_investment_invested') ?>" value="<?= $invested ?>">
				</td>
				<td class="interest-td">
					<input type="text" class="interest" tabindex="<?= $tabindex; ?>" name="interest-<?= $userId ?>" placeholder="<?= __('module_investment_interest') ?>" value="<?= $interest ?>">
				</td>
				<td class="gain-td">
					<input type="text" class="gain" name="gain-<?= $userId ?>" tabindex="-1" placeholder="<?= __('module_investment_gain') ?>" value="<?= $invested * $interest / 100 ?>" readonly="readonly">
				</td>
				<td>
					<input type="text" name="commission-<?= $userId ?>" tabindex="-1" placeholder="<?= __('module_investment_commision') ?>"<?php if ( 0 != $value->commission ) : ?> value="<?= $value->commission ?>"<?php endif; ?>>
				</td>
				<td>
					<input type="text" name="payment_date-<?= $userId ?>" tabindex="-1" placeholder="<?= __('module_investment_payment_date') ?>" value="<?= $value->payment_date ?>">
				</td>
				<td>
					<input type="text" name="note-<?= $userId ?>" tabindex="-1" placeholder="<?= __('note') ?>">
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
	<div class="col-xs-3 mt-15 save-view-buttons">
		<input type="submit" tabindex="<?= $tabindex + 1; ?>" value="<?= __('save') ?>" class="button">
	</div>
</form>
<script>
$('.interest').focusout((event) => {	
	let elm = $(event.target);
	var interest = elm.val();
	var invested = elm.parent().parent().find('.invested-td').find('.invested').val();
	elm.parent().parent().find('.gain-td').find('.gain').val(interest * invested / 100);
});
$('.invested').focusout(() => {
	let elm = $(event.target);
	var invested = elm.val();
	var interest = elm.parent().parent().find('.interest-td').find('.interest').val();
	elm.parent().parent().find('.gain-td').find('.gain').val(interest * invested / 100);
});
$(document).ready(() => {
	$('.table-default input[tabindex=1]')[0].focus();
	check('.cb-investment-head','.module_investment_editinvestment .cb-investment-list');
});
</script>