
<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_investment_header') ?></h2>
	</div>
	<div class="col-sm-6 action-submenu page-actions">
		<div class="action-new tile">
			<a href="/<?= Art_Router::getLayer() ?>/investment/new">
			<i class="fa fa-plus fa-2x"></i>
			<?= __('investment-add') ?></a>
		</div>
		<div class="action-new tile">
			<a href="/<?= Art_Router::getLayer() ?>/investment/newmonth">
				<i class="fa fa-calendar-plus-o fa-2x"></i>
				<?= __('investment-create') ?></a>
		</div>
		<div class="action-new tile">
			<a href="/<?= Art_Router::getLayer() ?>/investment/terminated">
				<i class="fa fa-file-excel-o fa-2x"></i>
				<?= __('terminated') ?></a>
		</div>
	</div>
</div>

<?= __('module_investment_default_interest') ?>: <b><?= $this->defaultInterest ?>%</b>
<?php if ( NULL !== $this->defaultInterestId ) : ?>
	(<a href="/<?= Art_Router::getLayer() ?>/default_value/edit/<?= $this->defaultInterestId ?>">upravit</a>)
<?php endif; ?>

<div class="investments-by-month">
	<?php foreach (array_reverse($this->links) as $key => $val) : ?>
		<a href="/<?= Art_Router::getLayer() ?>/investment/detail/<?= $key ?>">
			<i class="fa fa-calendar"></i>
			<?= $val ?>
		</a>
	<?php endforeach; ?>
</div>

<table class="table-default">
	<colgroup>
		<col class="w30">
		<col class="w10">
		<col class="w15">
		<col class="w15">
		<col class="w20">
		<col class="w10">
	</colgroup>
	<tr>
		<th>
			<?= Helper_Default::renderSortUpDown($this->sortBy, 'surname', __('fullname')) ?>
		</th>
		<th>
			<?= Helper_Default::renderSortUpDown($this->sortBy, 'value', __('module_investment_value')) ?>
		</th>
		<th>
			<?= Helper_Default::renderSortUpDown($this->sortBy, 'date',__('module_investment_date')) ?>
		</th>
		<th>
			<?= Helper_Default::renderSortUpDown($this->sortBy, 'expiry_date', __('module_investment_expiry_date')) ?>
		</th>
		<th>
			<?= __('module_investment_note') ?>
		</th>
		<th></th>
	</tr>
	<?php
	foreach ($this->deposit as $value) : /* @var $value Service_Investment_Deposit */
		if (!$value->terminated) :
	?>
		<tr>
			<td><?= Art_Filter::cutString($value->getUser()->fullname, 40) ?></td>
			<td><?= $value->value ?></td>
			<td><?= nice_date($value->date) ?></td>
			<td<?= (strtotime($value->expiry_date) < time() ) ? ' class="overdue"' : null ?>><?= nice_date($value->expiry_date) ?></td>
			<td><?= Art_Filter::cutString($value->note, 40) ?></td>
			<td>
				<div class="inline-actions">
					<a href="<?= $this->deposit_edit.$value->id ?>"><button><i class="fa fa-pencil edit"></i></button></a>
					<button <?= $this->delete_single_request->getHTML(array('id'=>$value->id)) ?> title="<?= __('delete') ?>"><i class="fa fa-trash-o"></i></button>
					<?php if ( $value->terminable ) : ?>
						<button <?= $this->terminate_single_request->getHTML(array('id'=>$value->id)) ?> title="<?= __('terminate') ?>"><i class="fa fa-ban"></i></button>
					<?php endif; ?>
				</div>
			</td>
		</tr>
	<?php
		endif;
	endforeach;
	?>
</table>