<h2><?= __('module_investment_new_deposit') ?></h2>

<form <?= $this->request->getHTML() ?> class="form">
	<div class="investment-new">
		<div class="row">
			<label><?= __('module_payments_payer') ?></label>
			<select class="chosen-select" name="id_user" tabindex="1" data-placeholder="Vyber">
				<?php foreach ($this->users as $user) : ?>
				<option value="<?= $user->id ?>"><?= $user->fullname ?></option>
				<?php endforeach; ?>
			</select>
		</div>	
		<div class="row pt-10">
			<label><?= __('module_investment_deposit_value') ?></label>
			<input type="text" name="value" placeholder="<?= __('module_investment_deposit_value') ?>">
		</div>
			
		<div class="row pt-10">
			<label>Datum vkladu</label>
			<input name="date" type="text" class="form-control" placeholder="0000-00-00"
					value="<?= $this->currentDate ?>">
		</div>	

		<div class="row pt-10">
			<label>Datum expirace</label>
			<input name="expiry_date" type="text" class="form-control" placeholder="0000-00-00"
					value="<?= $this->afterYearDate ?>">
		</div>

		<div class="row pt-10">
			<label>Poznámka</label>
			<input name="note" type="text" class="form-control">

		</div>
	</div>

	<div class="save-view-buttons mt-15">
		<input type="submit" value="<?= __('save') ?>" class="button">
	</div>
</form>
<script type="text/javascript">
$(document).ready(() => {
	$('.chosen-select').chosen({
		max_selected_options: -1
	});
	$('.chosen-container').removeClass('chosen-disabled');
});
</script>