
<div class="row">
    <div class="col-sm-6 action-name">
        <h2><?= __('module_investment_terminated_header') ?></h2>
    </div>
</div>

<table class="table-default">
    <colgroup>
		<col class="w20">
		<col class="w15">
		<col class="w15">
		<col class="w15">
		<col class="w15">
		<col class="f30">
	</colgroup>
    <tr>
        <th>
            <?= Helper_Default::renderSortUpDown($this->sortBy, 'surname') ?>
            <?= __('fullname') ?>
        </th>
        <th class="text-right">
            <?= Helper_Default::renderSortUpDown($this->sortBy, 'value') ?>
            <?= __('module_investment_value') ?>
        </th>
        <th>
            <?= Helper_Default::renderSortUpDown($this->sortBy, 'date') ?>
            <?= __('module_investment_date') ?>
        </th>
        <th>
            <?= Helper_Default::renderSortUpDown($this->sortBy, 'expiry_date') ?>
            <?= __('module_investment_expiry_date') ?>
        </th>
        <th colspan="2">            
            <?= __('module_investment_formal_termination_date') ?>
        </th>
    </tr>
    <?php foreach ($this->deposit as $value) : /* @var $value Service_Investment_Deposit */
            if ($value->terminated ) :
    ?>
    <tr>
        <td>
            <?= $value->getUser()->fullname ?></td>
        <td class="text-right">
            <?= money_format('%n',  $value->value) ?>
        </td>
        <td>
            <?= nice_date($value->date) ?>
        </td>
        <td>
            <?= nice_date($value->expiry_date) ?>
        </td>
        <td>
            <?= $value->formal_expiry_date ? nice_date($value->formal_expiry_date) : '' ?>
        </td>
        <td>
            <?php if (!empty($value->note)) : ?>
                <a href="javascript:;" data-toggle="tooltip" data-placement="left" title="<?= $value->note ?>"><i class="fa fa-comment edit"></i></a>
            <?php endif; ?>
        </td>
    </tr>
    <?php 
            endif;
        endforeach;
    ?>
</table>
<script>
$(document).ready(() => {	
	$('[data-toggle="tooltip"]').tooltip();
});
</script>