<h1>Administrace club.tbdevelopment.cz</h1>
<div class="dash-nav coming_soon">
				<div class="col-xs-3">
					<i class="fa fa-users"></i>
					<p>123 aktnivních členů</p>
				</div>
				<div class="col-xs-3">
					
					<i class="fa fa-envelope-o"><span class="badge">14</span></i>
					<p>Zprávy</p>
				</div>
				<div class="col-xs-3">
					<i class="fa fa-globe"><span class="badge">8</span></i>
					<p>Upozornění</p>
				</div>
				<div class="col-xs-3">
					<i class="fa fa-cogs"></i>
					<p>Nastavení účtu</p>
				</div>
			</div>
			<div class="row-fluid">
				<div class="col-xs-6 fast-box-border">
					<h4>Poslední příspěvky na nástěnce</h4>
					<div class="fast-box dashboard">
						 #[dashboard]#
					</div>
				</div>
				<div class="col-sm-6 fast-box-border coming_soon">
					<h4>Přehled zpráv</h4>
					<div class="fast-box">
						
					</div>
				</div>
			</div>
<?php /**
			<div class="row-fluid">
				<div class="col-sm-8 fast-box-border">
					<div class="fast-box">
						<h4>Nástěnka</h4>
					</div>
				</div>
				<div class="col-sm-4 fast-box-border">
					<div class="fast-box">
						<h4>Kalendář</h4>
						
					</div>
				</div>
			</div>
			<div class="clear last"></div>
			<div class="row-fluid">
				<h2>Seznam členu</h2>
				
				<div class="col-xs-6 np pt-10 pb-5"><p>Vypisovat <select><option>20</option><option>30</option></select> členů</p></div>
				<div class="col-xs-6 np text-right pt-10 pb-5">Stránka <i class="fa fa-arrow-left no-active"></i> <span class="page-number">1</span> <i class="fa fa-arrow-right"></i> z 12</div>
				<table class="table-default colored-rows">
					<tr>
						<th class="td-w60 text-center">ID <i class="fa fa-angle-down"></i><i class="fa fa-angle-up"></i></th>
						<th class="text-left">Jméno <i class="fa fa-angle-down"></i><i class="fa fa-angle-up"></i></th>
						<th class="text-left">Příjmení <i class="fa fa-angle-down"></i><i class="fa fa-angle-up"></i></th>
						<th class="text-left">Email</th>
						<th class="text-left">Adresa</th>
						<th class="text-left">Telefoní číslo</th>
						<th class="text-center">Členství od <i class="fa fa-angle-down"></i><i class="fa fa-angle-up"></i></th>
						<th class="text-center">Zaplaceno do <i class="fa fa-angle-down"></i><i class="fa fa-angle-up"></i></th>
						<th class="text-left">Služby</th>
						<th><i class="fa fa-pencil"></i></th>
					</tr>
					<tr>
						<td class="text-center">321</td>
						<td>Alexandr</td>
						<td>Karmazin</td>
						<td>karmazin@email.cz</td>
						<td>Azurova 16, Brno 602 00</td>
						<td>+420 737 212 790</td>
						<td class="text-center">10. 10. 1990</td>
						<td class="text-center">20. 11. 2032</td>
						<td><i class="fa fa-car"></i> <i class="fa fa-phone"></i> <i class="fa fa-pie-chart"></i></td>
						<td><i class="fa fa-pencil"></i></td>
					</tr>
					<tr>
						<td class="text-center">321</td>
						<td>Alexandr</td>
						<td>Karmazin</td>
						<td>karmazin@email.cz</td>
						<td>Azurova 16, Brno 602 00</td>
						<td>+420 737 212 790</td>
						<td class="text-center">10. 10. 1990</td>
						<td class="text-center">20. 11. 2032</td>
						<td><i class="fa fa-car"></i> <i class="fa fa-phone"></i> <i class="fa fa-pie-chart"></i></td>
						<td><i class="fa fa-pencil"></i></td>
					</tr>
					<tr>
						<td class="text-center">321</td>
						<td>Alexandr</td>
						<td>Karmazin</td>
						<td>karmazin@email.cz</td>
						<td>Azurova 16, Brno 602 00</td>
						<td>+420 737 212 790</td>
						<td class="text-center">10. 10. 1990</td>
						<td class="text-center">20. 11. 2032</td>
						<td><i class="fa fa-car"></i> <i class="fa fa-phone"></i> <i class="fa fa-pie-chart"></i></td>
						<td><i class="fa fa-pencil"></i></td>
					</tr>
					<tr>
						<td class="text-center">321</td>
						<td>Alexandr</td>
						<td>Karmazin</td>
						<td>karmazin@email.cz</td>
						<td>Azurova 16, Brno 602 00</td>
						<td>+420 737 212 790</td>
						<td class="text-center">10. 10. 1990</td>
						<td class="text-center">20. 11. 2032</td>
						<td><i class="fa fa-car"></i> <i class="fa fa-phone"></i> <i class="fa fa-pie-chart"></i></td>
						<td><i class="fa fa-pencil"></i></td>
					</tr>
				</table>
				<div class="col-xs-3 np pt-15"><p>Vypisovat <select><option>20</option><option>30</option></select> členů</p></div>
				<div class="col-xs-6 np text-center pt-15"><i class="fa fa-angle-double-left"></i> <strong>1</strong>, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 <i class="fa fa-angle-double-right"></i></div>
				<div class="col-xs-3 np text-right pt-15">Stránka <i class="fa fa-arrow-left no-active"></i> <span class="page-number">1</span> <i class="fa fa-arrow-right"></i> z 12</div>
		**/ ?>	