<?php if(Art_User::getRights()==0): ?>
<h3 class="text-center">Přihlášení</h3>
<form name="login-embedd" <?= $this->login_request->getHTML() ?>>
	<div class="linka"></div>
		<div class="input-border">
			<i class="fa fa-user fa-2x"></i><input name="email" type="text" class="form-control email" placeholder="<?= __('email') ?>">
		</div>
		<div class="input-border">
			<i class="fa fa-lock fa-2x"></i><input name="pass" type="password" class="form-control pass pass-input" placeholder="<?= __('password') ?>">
		</div>
	<div class="mt-10 mb-5 text-left pl-50"><a href="/forgotten">Zapomenuté heslo</a></div>
			<input type="submit" value="<?= __('log_in') ?>">
		
		<?php /*<a href="<?= Art_Server::getRelativePath()?>/registrace">Registrovat se</a> */?>
	
</form>
<?php else: ?>
<form name="login-embedd-logout" <?= $this->logout_request->getHTML() ?>>
	<div class="col-md-12 col-xs-12 text-center logout-box">
		<input type="submit" class="btn btn-info logout-button" value="<?= __('log_out') ?>">
	</div>
</form>
<?php endif; ?>
