<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_review_header') ?></h2>
	</div>
</div>

<?php if (count($this->reviews) > 0) : ?>
<table class="table-default">
	<colgroup>
		<col class="w20">
		<col class="w40">
		<col class="w40">
	</colgroup>
	<tr>
		<th><?= __('fullname') ?></th>
		<th><?= __('review') ?></th>
		<th><?= __('module_review_reply_body') ?></th>
	</tr>
	<?php 
		foreach ($this->reviews as $review) : 
	?>
		<tr>
			<td><?= $review->p_fullname ?></td>
			<td><a href="<?= $review->a_detail ?>"><?= $review->note ?></a></td>
			<td>
				<?= $review->reply ?>
				<div class="inline-actions">
					<a href="<?= $review->a_reply ?>"><?= (NULL == $review->reply) ? __('module_review_reply_do') : __('module_review_reply_edit') ?></a>
					<?php if ($review->visible) : ?>
						<button <?= $this->active_request->getHTML(array('id' => $review->id)) ?> title="<?= __('published') ?>"><i class="fa fa-eye"></i></button>
					<?php else: ?>
						<button <?= $this->active_request->getHTML(array('id' => $review->id)) ?> title="<?= __('unpublished') ?>"><i class="fa fa-eye-slash"></i></button>
					<?php endif; ?>
					<button <?= $this->delete_single_request->getHTML(array('id'=>$review->id,'fullname'=>$review->p_fullname)) ?> title="<?= __('delete') ?>"><i class="fa fa-trash-o"></i></button>
					</div>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
<?php else : ?>
<div class="empty-state reviews">
	<?= __('module_review_reviews_none'); ?>
</div>
<?php endif; ?>