<div class="background-white introduction-text">
	<?= Art_Widget::render('article', 'embedd', array('url_name' => $this->url_name)); ?>
</div>
<?php if (NULL !== $this->conditions) : ?>
	<div class="terms"><a href="<?= $this->conditions ?>" target="_blank"><?= __('module_service_pdf_conditions') ?></a></div>
<?php endif; ?>

<hr class="line-2colors">

<?php if ($this->isInvestment) : ?>
	<?php if (!empty($this->deposits)) : ?>
		<h3><?= __('module_users_deposits') ?></h3>
		<table class="table-default">
			<tr>
				<th><?= __('module_service_investment') ?></th>
				<th><?= __('module_investment_date') ?></th>
				<th><?= __('module_investment_expiry_date') ?></th>
			</tr>
			<?php foreach ($this->deposits as $value) :  ?>
				<tr>
					<td><?= $value->value ?> Kč</td>
					<td><?= nice_date($value->date) ?></td>
					<td><?= nice_date($value->expiry_date) ?></td>
				</tr>
			<?php endforeach; ?>
		</table>
		
		<hr class="line-2colors">
		
	<?php endif; ?>

	<h3><?= __('module_users_interests') ?></h3>
		
	<?php if ( !empty($this->investmentValues) ) : ?>
	<table class="table-default">
		<tr>
			<th><?= __('module_investment_month_year') ?></th>
			<th><?= __('module_investment_interest') ?></th>
			<th><?= __('module_investment_invested') ?></th>
			<th><?= __('module_investment_gain') ?></th>			
			<?php if ( $this->hasCommission ) : ?>
				<th><?= __('module_investment_commision') ?></th>
			<?php endif; ?>
			<th><?= __('module_investment_payment_date') ?></th>	
			<th><?= __('note') ?></th>
		</tr>
		
		<?php foreach ( $this->investmentValues as $value ): /* @var $value Service_Investment_Value */ ?>
		<tr>
			<td><?= Helper_Default::getCzechMonthName($value->investment->month).' '.$value->investment->year ?></td>
			<td><?= $value->interest ?>%</td>
			<td><?= $value->invested ?> Kč</td>
			<td><?= $value->invested * $value->interest / 100 ?> Kč</td>
			<?php if ( $this->hasCommission ) : ?>
				<td><?= $value->commission ?></td>
			<?php endif; ?>	
				<td><?= nice_date($value->payment_date) ?></td>
			<td><?= $value->note ?></td>
		</tr>
		<?php endforeach; ?>		
	</table>	
	<?php endif; ?>
<?php endif; ?>