	
<h2><?= __('module_service_payments') ?></h2>
	
	<?php foreach ( $this->payments as $payment ): /* @var $payment Service_Payment */ ?>
	
		<div class="col-md-3 col-xs-3"><?= $payment->service->name ?></div>
		<div class="col-md-3 col-xs-3"><?= $payment->paid_by_fullname ?></div>
		<div class="col-md-3 col-xs-3"><?= $payment->value ?></div>
		<div class="col-md-3 col-xs-3"><?= nice_date($payment->date) ?></div>
	
	<?php endforeach; ?>