<h2><?= __('module_users_companies_header') ?></h2>

<!-- <div class="row">
	<div class="col-sm-6 action-submenu">
		
		<div class="action-new">
			<a href="/<?= ''//Art_Router::getLayer() ?>/users/new">
			<i class="fa fa-plus fa-2x"></i>
			<?= ''//__('add') ?></a>
		</div>
	
	</div>
</div> -->

<div class="filter-container">
	<?= Art_Widget::render('filter', 'embeddCompany') ?>
</div>
	
<?php if (!empty($this->usersData)) : ?>	
	<table class="table-default table-list">
		<colgroup>
			<col class="w25">
			<col class="w25">
			<col class="f25">
			<col class="w10">
			<col class="w15">
		</colgroup>
		<tr>
			<!-- <th>
				<?= Helper_Default::renderSortUpDown($this->sortBy, 'id') ?>
				ID
			</th> -->
			<th>
				<?= Helper_Default::renderSortUpDown($this->sortBy, 'company_name') ?>
				<?= __('company_name') ?>
			</th>
			<th><?= __('email') ?></th>
			<th></th>
			<th>
				<?= Helper_Default::renderSortUpDown($this->sortBy, 'membership_from') ?>
				<?= __('module_users_membership_from') ?>
			</th>
			<th>
				<?= Helper_Default::renderSortUpDown($this->sortBy, 'membership_to') ?>
				<?= __('module_users_membership_to') ?>
			</th>
		</tr>
		
		<?php foreach ($this->usersData as $data) : /* @var $data Art_Model_User_Data */ ?>
		<tr>
			<td>
				<a href="<?= $data->a_detail ?>" class="company-name" data-toggle="tooltip" data-placement="bottom" title="ID: <?= $data->_user->user_number ?>"><?= $data->company_name ?></a>
				<div <?= $data->getUser()->active ? 'class="company-contact-person"' : 'class="company-contact-person overdue"' ?>>
					<?= $data->fullname ?>
				</div>
				<div class="services">
					<?php foreach( $data->services as $service ) : /* @var $service Service */ ?>
						<a href="<?= $data->a_service.$service->id ?>"<?= $serviceColor = in_array($service->type, $data->actServices) ? ' class="active"' : null ?>>
							<i class="fa fa-<?= $service->fa_icon ?>"></i>
						</a>
					<?php endforeach; ?>
				</div>
			</td>
			<td>
				<div><?= $data->email ?></div>
				<div><?= $data->p_phone ?></div>
			</td>
			<td class="text-center">
				<?=  Art_Widget::render('note', 'embedd', array('id_user' => $data->p_userId))  ?>
			</td>
			<td>
				<?= $data->membership_from ?>
			</td>
			<td>
				<?= $data->membership_to_colored ?>
				<div class="inline-actions">
					<a href="<?= $data->a_edit ?>"><i class="fa fa-pencil"></i></a>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</table>
<?php endif; ?>
		
<div>
	<?php echo __('module_users_count') . ': ' . $this->count ?>
</div>
	
<script>
$(document).ready(() => {
	$('.chosen-select').chosen({
		max_selected_options: -1
	});
	$('.chosen-container').removeClass('chosen-disabled');

	function filterRows (cellSelector) {
		let value = event.currentTarget.value;

		let tr = $("table.table-list").find("tr");

		tr.each((i, row) => $(row).removeClass('hide'));
		tr.each((index, row) => {
			if (index === 0) return;
			let name = $(row).find(`td:first-child a.${cellSelector}`).text();
			if (name.toLowerCase().indexOf(value) === -1)
				$(row).addClass('hide');
		});
	}

	$("#company-name").keyup((event) => {
		filterRows('company-name');
	});

    $('[data-toggle="tooltip"]').tooltip();
});
</script>