<h2><?= __('module_users_edit_user') ?></h2>

<div class="background-white">
<form <?= $this->request->getHTML() ?> class="form">
	<div class="col-xs-6">
		<div class="col-xs-12"><h3><?= __('module_users_company_info') ?></h3></div>
		<div class="col-xs-12">
		<input name="company_name" type="text" class="form-control" placeholder="<?= __('company_name') ?>"
				   value="<?= Helper_Default::getPropertyOrNull($this->companyAddress,'company_name') ?>">
		</div>
		<div class="col-xs-6 mt-20">
			<input name="ico" type="text" class="form-control" placeholder="<?= __('ico') ?>"
				   value="<?= Helper_Default::getPropertyOrNull($this->companyAddress,'ico') ?>">
		</div>	
		<div class="col-xs-6 mt-20">
			<input name="dic" type="text" class="form-control" placeholder="<?= __('dic') ?>"
				   value="<?= Helper_Default::getPropertyOrNull($this->companyAddress,'dic') ?>">
		</div>
	</div>
	<div class="col-xs-6">	
			<div class="col-md-12 col-xs-12"><h3><?= __('module_users_company_address') ?></h3></div>
	<div class="col-xs-7">
		<input name="<?= Art_Model_Address::COMPANY_PREFIX ?>street" type="text" class="form-control" placeholder="<?= __('street') ?>"
			   value="<?= Helper_Default::getPropertyOrNull($this->companyAddress,'street') ?>">
	</div>
	<div class="col-xs-5">
		<input name="<?= Art_Model_Address::COMPANY_PREFIX ?>housenum" type="text" class="form-control" placeholder="<?= __('house_number') ?>"
			   value="<?= Helper_Default::getPropertyOrNull($this->companyAddress,'housenum') ?>">
	</div>
	<div class="col-xs-7 mt-20">
		<input name="<?= Art_Model_Address::COMPANY_PREFIX ?>city" type="text" class="form-control" placeholder="<?= __('city') ?>"
			   value="<?= Helper_Default::getPropertyOrNull($this->companyAddress,'city') ?>">
	</div>	
	<div class="col-xs-3 mt-20">
		<input name="<?= Art_Model_Address::COMPANY_PREFIX ?>zip" type="text" class="form-control" placeholder="<?= __('zip_code') ?>"
			   value="<?= Helper_Default::getPropertyOrNull($this->companyAddress,'zip') ?>">
	</div>
	<div class="clearfix"></div>
	<div class="col-xs-7 mt-20">
		<div class="form-group">
		  <select class="form-control" id="country1" name="<?= Art_Model_Address::COMPANY_PREFIX ?>country">
			<?php foreach ($this->countryList as $country) : ?>
			  <option value="<?= $country->id ?>"<?= 
				  Helper_Default::getSelectedOrNull($this->companyAddress,'id_country',$country->id) ?>
					  ><?= $country->name ?></option>
			<?php endforeach; ?>
		  </select>
		</div>
	</div>
	</div> 
	<div class="clearfix"></div>
	<div class="col-xs-6">	
		<div class="col-xs-12"><h3><?= __('module_users_auth_person_address') ?></h3></div>		
			
		<div class="col-xs-7">
			<input name="<?= Module_Users::AUTH_PERSON ?>street" type="text" class="form-control" placeholder="<?= __('street') ?>"
				   value="<?= $this->deliveryAddress->street ?>">
		</div>		
		<div class="col-xs-5">
			<input name="<?= Module_Users::AUTH_PERSON ?>housenum" type="text" class="form-control" placeholder="<?= __('house_number') ?>"
				   value="<?= $this->deliveryAddress->housenum ?>">
		</div>
		<div class="col-xs-7 mt-20">
			<input name="<?= Module_Users::AUTH_PERSON ?>city" type="text" class="form-control" placeholder="<?= __('city') ?>"
				   value="<?= $this->deliveryAddress->city ?>">
		</div>
		<div class="col-xs-3 mt-20">
			<input name="<?= Module_Users::AUTH_PERSON ?>zip" type="text" class="form-control" placeholder="<?= __('zip_code') ?>"
				   value="<?= $this->deliveryAddress->zip ?>">
		</div>
		<div class="col-xs-7 mt-20">
			  <select class="form-control" id="country1" name="<?= Module_Users::AUTH_PERSON ?>country">
				<?php foreach ($this->countryList as $country) : ?>
				  <option value="<?= $country->id ?>"<?= 
						Helper_Default::getSelectedOrNull($this->deliveryAddress,'id_country',$country->id) ?>
							><?= $country->name ?></option>
				<?php endforeach; ?>
			  </select>
		</div>

		<div style="clear: both"></div>

		
	</div>
	<div class="col-xs-6">
		<div class="col-xs-12">
			<h3>Osobní údaje</h3>
		</div>
		<div class="col-xs-2">
			<input name="<?= Module_Users::AUTH_PERSON ?>degree" type="text" class="form-control" placeholder="<?= __('degree') ?>" 
				   value="<?= $this->data->degree ?>">
		</div>

		
		<div class="col-xs-5">
			<input name="<?= Module_Users::AUTH_PERSON ?>name" type="text" class="form-control" placeholder="<?= __('firstname') ?>"
				   value="<?= $this->data->name ?>">
		</div>

		
		<div class="col-xs-5">
			<input name="<?= Module_Users::AUTH_PERSON ?>surname" type="text" class="form-control" placeholder="<?= __('surname') ?>"
				   value="<?= $this->data->surname ?>">
		</div>	
		<?php if ( $this->isRepresentantSame ) : ?>
			<div class="col-xs-12 mt-20">
				<input name="person-function" type="text" class="form-control" placeholder="<?= __('person_function') ?>"
					   value="<?= $this->representantFunction ?>">
			</div>
		<?php endif; ?>
		<div class="col-md-3 col-xs-3 lh-35 mt-20"><?= __('gender') ?></div>
		<div class="col-md-4 col-xs-4 lh-35 mt-20">
			<input id="gender-male" name="<?= Module_Users::AUTH_PERSON ?>gender" type="radio" value="1"
			<?= Helper_Default::getCheckedOrNull($this->data,'gender',0) ?>>
			<label for="gender-male"><?= __('male') ?></label>
		</div>
		<div class="col-md-4 col-xs-4 lh-35 mt-20">
			<input id="gender-female" name="<?= Module_Users::AUTH_PERSON ?>gender" type="radio" value="0"
				<?= Helper_Default::getCheckedOrNull($this->data,'gender',0) ?>>
			<label for="gender-female"><?= __('female') ?></label>
		</div>	
		
		<div class="col-md-2 col-xs-2 pt-20 mt-20"><?= __('born_date') ?></div>		
		<div class="col-md-10 col-xs-10 mt-20">
			<div class="col-sm-4">
				<div class="form-group">
				  <label for="day"><?= __('day') ?></label>
				  <select id="day" name="<?= Module_Users::AUTH_PERSON ?>born_day">
					<?php foreach ($this->days as $day) : ?>
					  <option value="<?= $day ?>"<?= 
							Helper_Default::getSelectedOrNull($this->data,'born_day',$day) ?>
							  ><?= $day ?></option>
					<?php endforeach; ?>
				  </select>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="form-group">
				  <label for="month"><?= __('month') ?></label>
				  <select class="form-control" id="month" name="<?= Module_Users::AUTH_PERSON ?>born_month">
					<?php foreach ($this->months as $month) : ?>
					  <option value="<?= $month ?>"<?= 
							Helper_Default::getSelectedOrNull($this->data,'born_month',$month) ?>
							  ><?= $month ?></option>
					<?php endforeach; ?>
				  </select>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="form-group">
				  <label for="year"><?= __('year') ?></label>
				  <select class="form-control" id="year" name="<?= Module_Users::AUTH_PERSON ?>born_year">
					<?php foreach ($this->years as $year) : ?>
					  <option value="<?= $year ?>"<?= 
							Helper_Default::getSelectedOrNull($this->data,'born_year',$year) ?>
							  ><?= $year ?></option>
					<?php endforeach; ?>
				  </select>
				</div>
			</div>
		</div>
	</div>
		
		
	
		
		
		
	<?php if ( !$this->isRepresentantSame ) : ?>
	<div class="col-xs-6">	
		<div class="col-xs-12"><h3><?= __('module_users_representant_person_info') ?></h3></div>
		
		
		<div class="col-xs-2">
			<input name="degree" type="text" class="form-control" placeholder="<?= __('degree') ?>" 
				   value="<?= $this->representantData->degree ?>">
		</div>

		<div class="col-xs-5">
			<input name="name" type="text" class="form-control" placeholder="<?= __('firstname') ?>"
				   value="<?= $this->representantData->name ?>">
		</div>
		<div class="col-xs-5">
			<input name="surname" type="text" class="form-control" placeholder="<?= __('surname') ?>"
				   value="<?= $this->representantData->surname ?>">
		</div>	
		<div class="col-xs-12 mt-20">
			<input name="person-function" type="text" class="form-control" placeholder="<?= __('person_function') ?>"
				   value="<?= $this->representantFunction ?>">
		</div>
		<div class="col-md-3 col-xs-3 lh-35 mt-20"><?= __('gender') ?></div>
		<div class="col-md-4 col-xs-4 lh-35 mt-20">
			<input name="gender" type="radio" value="1" checked="checked">
			<?= __('male') ?>
		</div>
		<div class="col-md-4 col-xs-4 lh-35 mt-20">
			<input name="gender" type="radio" value="0"
				<?= Helper_Default::getCheckedOrNull($this->representantData,'gender',0) ?>>
			<?= __('female') ?>
		</div>	
		
		<div class="col-md-2 col-xs-2 pt-20 mt-20"><?= __('born_date') ?></div>		
		<div class="col-md-10 col-xs-10 mt-20">
			<div class="col-sm-4">
				<div class="form-group">
				  <label for="day"><?= __('day') ?></label>
				  <select id="day" name="born_day">
					<?php foreach ($this->days as $day) : ?>
					  <option value="<?= $day ?>"<?= 
							Helper_Default::getSelectedOrNull($this->representantData,'born_day',$day) ?>
							  ><?= $day ?></option>
					<?php endforeach; ?>
				  </select>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="form-group">
				  <label for="month"><?= __('month') ?></label>
				  <select class="form-control" id="month" name="born_month">
					<?php foreach ($this->months as $month) : ?>
					  <option value="<?= $month ?>"<?= 
							Helper_Default::getSelectedOrNull($this->representantData,'born_month',$month) ?>
							  ><?= $month ?></option>
					<?php endforeach; ?>
				  </select>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="form-group">
				  <label for="year"><?= __('year') ?></label>
				  <select class="form-control" id="year" name="born_year">
					<?php foreach ($this->years as $year) : ?>
					  <option value="<?= $year ?>"<?= 
							Helper_Default::getSelectedOrNull($this->representantData,'born_year',$year) ?>
							  ><?= $year ?></option>
					<?php endforeach; ?>
				  </select>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-6">
		<div class="col-md-12 col-xs-12"><h3><?= __('module_users_representant_person_address') ?></h3></div>
		
		<div class="col-xs-7">
			<input name="<?= Art_Model_Address::DELIVERY_PREFIX ?>street" type="text" class="form-control" placeholder="<?= __('street') ?>"
				   value="<?= $this->representantAddress->street ?>">
		</div>		
		<div class="col-xs-5">
			<input name="<?= Art_Model_Address::DELIVERY_PREFIX ?>housenum" type="text" class="form-control" placeholder="<?= __('house_number') ?>"
				   value="<?= $this->representantAddress->housenum ?>">
		</div>
		<div class="col-xs-7 mt-20">
			<input name="<?= Art_Model_Address::DELIVERY_PREFIX ?>city" type="text" class="form-control" placeholder="<?= __('city') ?>"
				   value="<?= $this->representantAddress->city ?>">
		</div>	
		<div class="col-xs-3 mt-20">
			<input name="<?= Art_Model_Address::DELIVERY_PREFIX ?>zip" type="text" class="form-control" placeholder="<?= __('zip_code') ?>"
				   value="<?= $this->representantAddress->zip ?>">
		</div>
		<div class="col-xs-6 mt-20">
			  <select class="form-control" id="country1" name="<?= Art_Model_Address::DELIVERY_PREFIX ?>country">
				<?php foreach ($this->countryList as $country) : ?>
				  <option value="<?= $country->id ?>"<?= 
						Helper_Default::getSelectedOrNull($this->representantAddress,'id_country',$country->id) ?>
							><?= $country->name ?></option>
				<?php endforeach; ?>
			  </select>
		</div>	
<div style="clear: both"></div>
	</div>
	
	
<?php endif; ?>	
	<div class="clearfix"></div>	
		
	<div class="col-xs-6 mb-30">
		<div class="col-xs-12">
			<h3>Kontaktní údaje</h3>
		</div>
		<div class="col-md-3 col-xs-3"><?= __('phone_number') ?></div>
		<div class="col-md-3 col-xs-3">
			<input name="<?= Module_Users::AUTH_PERSON ?>area_code" type="text" class="form-control" placeholder="<?= __('area_number') ?>" title="<?= __('module_registration_area_number_title') ?>"
						value="<?= $this->deliveryAddress->area_code ?>">
		</div>
		<div class="col-xs-6"><input name="<?= Module_Users::AUTH_PERSON ?>phone" type="text" class="form-control" placeholder="<?= __('phone_number') ?>"
									 value="<?= $this->deliveryAddress->phone ?>"></div>
		
		<div style="clear: both"></div>
		<div class="col-md-3 col-xs-3 lh-35 mt-20"><?= __('email') ?></div>
		<div class="col-xs-9 mt-20">
			<input name="email" type="email" class="form-control" placeholder="<?= __('email') ?>"
			   value="<?= $this->data->email ?>">
		</div>
		<div class="clearfix"></div>
	</div>

	<div class="clearfix"></div>
</div>	
	<div class="save-view-buttons mt-20">
		<input type="submit" class="button" value="<?= __('save') ?>">
	</div>
</form>
