	
	<div class="user">
		<i>
			<?= icon('user-' . $this->user->gender); ?>
		</i>
		<?php
		echo sprintf("<em>%s</em>", $this->user->fullname); 

		if ($this->user->isManager) {
			echo sprintf("<span>%s</span>", __('manager'));
		}
		if ($this->user->isSupervisor) {
			echo sprintf("<span>%s</span>", __('supervisor'));
		}

		?>
	</div>
	<div class="actions">
		<?= Art_Widget::render('login', 'embedd', array('size' => 'small')); ?>
	</div>