
<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_users_header') ?></h2>
	</div>
	<div class="col-sm-6 action-submenu">
	<!--	
		<div class="action-new">
			<a href="/<?= ''//Art_Router::getLayer() ?>/users/new">
			<i class="fa fa-plus fa-2x"></i>
			<?= ''//__('add') ?></a>
		</div>
	-->
	</div>
</div>

<?php if ($this->count > 10) : ?>
<div class="table-filter collapsed">
	<?= Art_Widget::render('filter') ?>
	<div class="filter-handle">
		<?= __('module_filter_quick_header') ?>
	</div>
</div>
<?php endif; ?>
	
<?php if (!empty($this->usersData)) : ?>	
	<table class="table-default table-list" data-sortable>
		<colgroup>
			<col class="w30">
			<col class="w25">
			<col class="f30">
			<col class="w15">
			<col class="w15">
		</colgroup>
		<thead>
			<tr>
				<th>
					<span><?= __('firstname') ?> / <?= __('surname') ?></span>
				</th>
				<th data-sortable="false">
					<?= __('email') ?>
					/
					<?= __('phone_number') ?>
				</th>
				<th data-sortable="false"></th>
				<th>
					<span><?= __('module_users_membership_from') ?></span>
				</th>
				<th>
					<span><?= __('module_users_membership_to') ?></span>
				</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach( $this->usersData as $data ) : ?>
			<tr<?= $data->getUser()->active ? '' : ' class="inactive"' ?>>
				<td data-value="<?= $data->surname ?>">
					<a href="<?= $data->a_detail ?>" class="contact-person" data-toggle="tooltip" data-placement="bottom" title="ID: <?= $data->_user->user_number ?>">
						<span class="first-name"><?= $data->name ?></span>
						<span class="last-name"><?= $data->surname ?></span>
					</a>
					
					<div class="services">
						<?php foreach( $data->services as $service ) : ?>
							<a href="<?= $data->a_service.$service->id ?>"<?= $serviceColor = in_array($service->type, $data->actServices) ? ' class="active"' : null ?> data-service-id="<?= $service->id; ?>">
								<i class="fa fa-<?= $service->fa_icon ?>"></i>
							</a>
						<?php endforeach; ?>
					</div>
				</td>
				<td>
					<div><span class="email"><?= $data->email ?></span></div>
					<div><?= $data->p_phone ?></div>
				</td>
				<td class="text-center">
					<?= Art_Widget::render('note', 'embedd', array('id_user' => $data->p_userId)) ?>
				</td>
				<td data-value="<?= $data->membership_from_unixtime ?>">
					<?= $data->membership_from ?>
				</td>
				<td data-value="<?= $data->membership_to_unixtime ?>">
					<?= $data->membership_to_colored ?>
					<div class="inline-actions">
						<a href="<?= $data->a_edit ?>"><i class="fa fa-pencil"></i></a>
					</div>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>
		
	<div>
		<?php echo __('module_users_count') . ': ' . $this->count ?>
	</div>
	
<script>
$(document).ready(() => {
	$('.chosen-select').chosen({
		max_selected_options: -1
	});
	
	function filterRows (cellSelector) {
		let value = event.currentTarget.value;

		let tr = $("table.table-default").find("tr");

		tr.each((i, row) => $(row).removeClass('hide'));
		tr.each((index, row) => {
			if (index === 0) return;
			let name = $(row).find(`td ${cellSelector}`).text();
			if (name.toLowerCase().indexOf(value) === -1)
				$(row).addClass('hide');
		});
	}

	const filterRowsByService = (serviceId) => {
		const tr = $('table.table-default').find('tbody tr');
		tr.each((i, row) => serviceId == 0 ? $(row).removeClass('hide') : $(row).addClass('hide'));
		$(`table.table-default tbody tr td .services a.active[data-service-id="${serviceId}"]`).each ((i, item) => {
			let row = $(item).closest('tr').first();
			row.removeClass('hide');			
		});
	}

	$("#filter-lastname").keyup((event) => {
		filterRows('.last-name');
	});
	$("#filter-email").keyup((event) => {
		filterRows('.email');
	});
	
	$('[data-toggle="tooltip"]').tooltip();

	if ($('.table-filter')) {
		$('.table-filter .filter-handle').click((event) => {
			event.preventDefault();
			event.stopPropagation();

			$(event.currentTarget).parent().toggleClass('collapsed');
			$('.chosen-container').removeClass('chosen-disabled');
			$(event.currentTarget).parent().find('.chosen-container').each((i, ct) => {
				   $(ct).attr('style', 'width: 100%');
			});
			$('#filter-service-type').on('change', (event, params) => {				
				filterRowsByService(params.selected);
			});
		});
	}
});
</script>