<h2><?= __('module_users_generate_new_code') ?></h2>

<form <?= $this->add_invite_code_request->getHTML() ?> class="form">
	<div class="filter generate-invite-code">
		<div>
			<label for="filter-company-name"><?= __('module_users_inv_code_user') ?></label>
			<select id="filter-company-name" class="chosen-select" name="user-id">
				<?php foreach ($this->usersData as $userData) : ?>
				  <option value="<?= $userData->id_user ?>"><?= $userData->fullname ?></option>
				<?php endforeach; ?>
			  </select>
		</div>
		<div>
			<label for="filter-note"><?= __('module_users_inv_code_note') ?></label>
			<input name="note" type="text" class="form-control">
		</div>
		<div class="submit">
			<input type="submit" class="button" value="<?= __('module_users_inv_code_generate_new') ?>">
		</div>
	</div>
</form>

<hr class="separator">

<h3><?= __('module_users_inv_code_current_codes') ?></h3>
<table class="table-default">
	<colgroup>
		<col class="w20">
		<col class="w40">
		<col class="w20">
		<col class="20">
	</colgroup>
	<tr>
		<th><?= __('module_users_code_owner') ?></th>
		<th><?= __('code') ?></th>
		<th><?= __('module_users_created_by') ?></th>
		<th><?= __('note') ?></th>
	</tr>
	
	<?php foreach ($this->codes as $value) : ?>
	<tr>
		<td><?= $value->fullname ?></td>
		<td><?= $value->URL ?></td>
		<td><?= $value->gen_by_fullname ?></td>
		<td><?= $value->note ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<script>
	$(document).ready(() => {
			$('.chosen-select').chosen({
				max_selected_options: -1
			});
			$('.chosen-container').removeClass('chosen-disabled');
	});
</script>