<h2><?= __('module_users_request_about') . $this->service->name ?></h2>

<div class="list mb-30">
	<div class="cell invested-amount">
		<em><?= $this->userData->fullname ?></em>
		<label><?= $this->userPhone ?></label>
	</div>
</div>
	
<h3><?= __('module_users_create_mail') ?></h3>
<form  <?= $this->sendRequest->getHTML() ?> class="form">
	<div class="email-new">
		<div class="row">
			<label for="mailto"><?= __('mail-subject') ?></label>
			<input id="mailto" name="mailto" type="text" disabled value="<?= $this->userData->email ?>">
		</div>
		<div class="row pt-15">
			<label for="subject"><?= __('mail-subject') ?></label>
			<input id="subject" name="subject" type="text" class="form-control" placeholder="<?= __('mail-subject') ?>">
		</div>
		<div class="row pt-15">
			<label for="body"><?= __('mail-body') ?></label>
			<textarea id="body" name="body" class="form-control" rows="8" placeholder="<?= __('mail-body') ?>"></textarea>
		</div>
	</div>
	<div class="save-view-buttons mt-15">
		<input type="hidden" value="<?= $this->email ?>">
		<input type="submit" class="button" value="<?= __('module_users_send') ?>">
	</div>
</form>