<h2><?= __('module_users_service_detail') ?> <?= $this->user->fullname ?></h2>

<div class="card-container service-detail">
	<aside class="user-details">
		<h4><?= __('module_users_personal_info') ?></h4>
		<label><?= __('fullname') ?></label>
		<div><?= $this->user->fullname ?></div>
		<label><?= __('phone_number') ?></label>
		<div><?= $this->phone ?></div>
		<label><?= __('email') ?></label>
		<div><?= $this->data->email ?></div>
		<hr>
		<h4><?= __('module_users_service_info') ?></h4>
		<label><?= __('module_users_service_type') ?></label>
		<div><?= $this->service->name ?></div>
		<label><?= __('from') ?></label>
		<div><?= $this->service->active_from ?></div>
		<label><?= __('to') ?></label>
		<div><?= $this->service->active_to ?></div>
		<label><?= __('module_users_service_actual_price') ?></label>
		<div><?= $this->service->actual_price ?></div>
		<label><?= __('module_users_service_time_interval') ?></label>
		<div><?= $this->service->time_interval ?></div>
	</aside>
	<main class="table-list">
		<?php if (!empty($this->payments)) : ?>
			<h4><?= __('module_users_payments') ?></h4>
			<ul>
				<?php foreach ($this->payments as $payment) : ?>
				<li>
					<?= nice_date(substr($payment->created_date,0,10)) ?><br>
					<?= __('module_payments_payer'); ?>
					<b><?= $payment->paid_by_fullname ?></b>
					<?= __('module_payments_paid_for'); ?>
					<b><?= $payment->service->name ?>,</b>
					<b><?= money_format('%n', $payment->value) ?></b>

				</li>
				<?php endforeach; ?>
			</ul>	
		<?php endif; ?>

		<?php if ($this->isInvestment) : ?>
			<?php if (!empty($this->deposits)) : ?>
				<h4><?= __('module_users_deposits') ?></h4>
				<ul>
					<?php foreach ($this->deposits as $value) : ?>
					<li>
						<?= nice_date($value->date) ?>
						<?= __('module_investment_date_added') ?>
						<b><?= money_format('%n', $value->value) ?></b>.
						<?= __('module_investment_date_will_expire') ?>
						<?= nice_date($value->expiry_date) ?>
					</li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>

			<?php if (!empty($this->investmentValues)) : ?>
				<hr>
				<h4><?= __('module_users_interests') ?></h4>
				<ul class="timeline-list">
					<?php foreach ($this->investmentValues as $value) : ?>
					<li>
						V měsíci
						<b><?= Helper_Default::getCzechMonthName($value->investment->month) . '/' . $value->investment->year ?></b>
						byl úrok ve výši
						<b><?= $value->interest ?>%</b>.<br>
						Z ivestice
						<?= money_format('%n', $value->invested) ?>
						bylo dne
						<?= $value->payment_date ?>
						vyplaceno
						<b><?= money_format('%n', $value->invested * $value->interest / 100) ?></b>
						<?php if ($this->hasCommission) : ?>
						(<?= $value->commission ?> <?= __('module_investment_commision') ?>)
						<?php endif; ?>
						<?php if (!empty($value->note)) : ?>
							<br><em><?= $value->note ?></em>
						<?php endif; ?>
					</li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		<?php endif; ?>
	</main>
</div>
