<nav role="navigation" class="navbar navbar-default mymenu">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
		   <span class="sr-only">Toggle navigation</span>
		   <span class="icon-bar"></span>
		   <span class="icon-bar"></span>
		   <span class="icon-bar"></span>
		</button>
		<div class="btn-group">
			<button class="btn btn-default btn-sm dropdown-toggle mesto" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<span class="nazev_mesta">Brno</span>
					<span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
				<li><a href="#">Action</a></li>
				<li><a href="#">Another action</a></li>
				<li><a href="#">Something else here</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="#">Separated link</a></li>
			</ul>
		</div>
	</div>
	<!-- Collection of nav links and other content for toggling -->
	<div id="navbarCollapse" class="collapse navbar-collapse">
		<ul class="nav navbar-nav">

		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li><a href="/kategorie/cestovani">Cestování</a></li>
			<li><a href="/kategorie/zdravi-a-krasa">Zdraví a krása</a></li>
			<li><a href="/kategorie/jidlo">Jídlo</a></li>
			<li><a href="/kategorie/volny-cas">Volný čás</a></li>
			<li><a href="/kategorie/produkty">Produkty</a></li>
		</ul>
	</div>
</nav>