
<h2><?= __('review') ?></h2>

<div class="col-xs-6 pl-0">
	<p class="text-justify ml-0">Napište nám sem Vaši vlastní recenzi na náš klub, vyjádřete svůj názor na naše služby a náš přístup. Vaše recenze poté bude automaticky zobrazena na našich hlavních webových stránkách. Ty, které tam již máme, jsou tedy 100% autentické. Na vaši recenzi dokonce obdržíte odpověď od některého správce z týmu TBDI.
		<br><br>Samozřejmě recenzi na webu nezobrazíme úplně ihned, bude ji muset schválit některý z našich administrátorů. Je to způsobeno tím, že existují vtipálci, které například baví zveřejňování vulgarit a ty bychom na našich stránkách zobrazovali neradi. </p>
</div>

<div class="col-xs-6">
<?php if ($this->sended) : ?>

	<div class="col-xs-12"><h3>Vaše recenze</h3></div>
	<div class="col-xs-12">
		<?= $this->review->note ?>
	</div>
	
	<div class="col-xs-12 mt-20"><h3><?= __('module_review_reply_body') ?></h3></div>
	<div class="col-xs-12">
		<?= $this->review->reply ?>
	</div>

<?php else : ?>

	<form <?= $this->request->getHTML() ?>>
		
		<div class="col-xs-12">
			<textarea name="body" class="form-control" placeholder="<?= __('module_review_body') ?>" rows="5"></textarea>
		</div>
		<div class="clearfix"></div>
		<input type="submit" class="btn btn-info" style="float: right; margin-right: 17px; margin-top: 17px;" value="<?= __('save') ?>">
	</form>
	
<?php endif; ?>
</div>
