<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
<head>
	<meta charset="UTF-8">
	<?= Art_Template::renderMeta() ?>
	<meta name="viewport" content="width=1200 initial-scale=0.5" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link rel="icon" href="/favicon.png">
	<?= Art_Template::loadExtensions(array( 'bootstrap','ckeditor' )) ?>
	<?= Art_Template::renderCSS(array( 'system.less', 'style.less' )); ?>
	<?= Art_Template::renderJS(); ?>
</head>
<body>
    <div id="alertBox"></div>
    <div class="celar"></div>
	
	
	<div class="head-bar">
		<div class="col-xs-3 text-left">
			<a href="/<?= Art_Router::getLayer() ?>">
			TB Development & Investmet
			</a>
		</div>
		<div class="col-xs-4">
		</div>
		<div class="col-xs-5 np">
			<div class="col-xs-5 text-left np h50">
				<div class="calendar-border">
					<div id="calendar" aria-haspopup="true" aria-expanded="true" class="dropdown-toggle">
						<button class="small-ico"><i class="fa fa-calendar"></i></button>
					</div>
					<div class="dropdown-menu calendar-box" aria-labelledby="calendar">
						<?php /** <div data-tockify-component="mini" data-tockify-calendar="alexcalendar"></div>
						<script data-tockify-script="embed" src="https://public.tockify.com/browser/embed.js"></script> **/  ?>
					</div>
				</div>
			</div>
			<?= Art_Widget::render('users', 'embedd'); ?>
			
		</div>
	</div>
	<div class="page-border">
		<div class="menu">
			<?= Art_Template::renderModuleContainer('menu') ?>
			
		</div>
		<div class="page">
			<?= Art_Template::renderContent() ?>
			
			
			<div class="clear last"></div>
		</div>
		
		
			</div>

</body>
</html>