<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
<head>
	<meta charset="UTF-8">
	<?= Art_Template::renderMeta() ?>
	<meta name="viewport" content="width=1200 initial-scale=0.5" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link rel="icon" href="/favicon.png">
	<?= Art_Template::loadExtensions(array('jquery', 'bootstrap', 'ckeditor', 'date-picker', 'chosen', 'sortable')) ?>
	<?= Art_Template::renderCSS(array('system.less', 'style.less')); ?>
	<?= Art_Template::renderJS(); ?>
</head>
<body>
    <!-- <div id="alertBox"></div>
    <div class="celar"></div>
	 -->
	<?php /*
	<div class="head-bar">
		<div class="app-name">
			<a href="/<?= Art_Router::getLayer() ?>">
			TB Development &amp; Investment
			</a>
		</div>
		<div class="profile">
			<?= Art_Widget::render('users', 'embedd'); ?>
		</div>
	</div>
	*/
	?>
	<div class="page-border">
		<aside class="menu">
			<?= Art_Template::renderModuleContainer('menu') ?>	
		</aside>
		<header class="header">
			<?= Art_Widget::render('users', 'embedd'); ?>
		</header>
		<main class="page">
			<?= Art_Template::renderContent() ?>
		</main>
	</div>	
</body>
</html>