<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
<head>
	<meta charset="UTF-8">
	<?= Art_Template::renderMeta() ?>
	<meta name="viewport" content="width=1200 initial-scale=0.5" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link rel="icon" href="/favicon.png">
	<?= Art_Template::loadExtensions(array('jquery', 'bootstrap','ckeditor', 'date-picker')) ?>
	<?= Art_Template::renderCSS(array( 'system.less', 'style.less' )); ?>
	<?= Art_Template::renderJS(); ?>
</head>
<body>
    <div id="alertBox"></div>
    <div class="celar"></div>
	
	<div class="head-bar">
		<div class="app-name">
			<a href="/<?= Art_Router::getLayer() ?>">
			TB Development &amp; Investment
			</a>
		</div>
		<div class="profile">
			<?= Art_Widget::render('users', 'embedd'); ?>
		</div>
	</div>
	<div class="page-border">
		<div class="menu">
			<?= Art_Template::renderModuleContainer('menu') ?>	
		</div>
		<div class="page">
			<?= Art_Template::renderContent() ?>
			<div class="clear last"></div>
		</div>
	</div>
</body>
</html>