<h2><?= __('module_service_request_header') ?></h2>

<form <?= $this->request->getHTML() ?> class="form">
	<div class="row">
		<label><?= __('module_user_group_service') ?></label>
		<input type="text" value="<?= $this->service->name ?>" disabled>
	</div>

	<div class="row pt-15">
		<label><?= __('module_service_request_person') ?></label>
		<input type="text" value="<?= $this->user->fullname ?>" disabled>
	</div>

	<div class="row pt-15"
		<label><?= __('module_service_from') ?></label>
		<input type="text" name="from_date" value="<?= date("Y-m-d") ?>" class="js-date-picker">
	</div>
	
	<div class="save-view-buttons mt-15">
		<input name="type" type="hidden" value="<?= $this->type ?>">
		<input type="submit" class="button" value="<?= __('pass') ?>">
	</div>
</form>

<script type="text/javascript">
$(document).ready(() => {
	$('.js-date-picker').click(() => {
		$('.js-date-picker').pickadate({
			format: 'yyyy-mm-dd'
		});
	});
});
</script>