<form <?= $this->request->getHTML() ?>>	
	
	<div class="col-xs-3">	
		<?= __('module_user_group_service') ?>
	</div>
	<div class="col-xs-3">
		  <?= $this->service->name ?>	
	</div>
	
	<div style="clear: both;"></div>
	
	<div class="col-xs-3">	
		<?= __('fullname') ?>
	</div>
	<div class="col-xs-3">
		  <?= $this->user->fullname ?>	
	</div>

	<div style="clear: both;"></div>
	
	<div class="col-md-2 col-xs-2 lh-35"><?= __('module_service_from') ?></div>	
	<div class="col-xs-1">
		<select name="from_day">
			<?php foreach ($this->days as $day) : ?>
				  <option value="<?= $day ?>"
					<?= Helper_Default::getSelectedOrNull($this,'currentDay',$day) ?>
						  ><?= $day ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	<div class="col-xs-1">
		<select name="from_month">
			<?php foreach ($this->months as $month) : ?>
				  <option value="<?= $month ?>"
						  <?= Helper_Default::getSelectedOrNull($this,'currentMonth',$month) ?>
						  ><?= $month ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	
	<div class="col-xs-2">
		<select name="from_year">
			<?php foreach ($this->years as $year) : ?>
				  <option value="<?= $year ?>"
						  <?= Helper_Default::getSelectedOrNull($this,'currentYear',$year) ?>
						  ><?= $year ?></option>
				<?php endforeach; ?>
		</select>
	</div>
	
	<div class="col-xs-3 text-right">
		<input name="type" type="hidden" value="<?= $this->type ?>">
		<input type="submit" class="btn" value="<?= __('save') ?>">
	</div>
</form>
