<h2><?= __('module_service_new_service') ?></h2>
<div class="background-white pa-15">
	<form <?= $this->request->getHTML() ?>>
		<div class="col-xs-6 np">
			<div class="col-xs-6" style="padding-left: 0px;">
				<input type="text" name="type" placeholder="<?= __('module_service_type') ?>">
			</div>
			<div class="col-xs-6">
				<input type="text" name="name" placeholder="<?= __('module_service_name') ?>">
			</div>
		
			<div class="col-xs-4 mt-15" style="padding-left: 0px;">
				<input type="text" name="price" placeholder="<?= __('module_service_price_price') ?>">	
			</div>
			<div class="col-xs-4 mt-15">
					<input type="text" name="time_interval_value" placeholder="<?= __('module_service_price_time_interval_value') ?>">
			</div>
			<div class="col-xs-4 mt-15">
				<select name="time_interval_type">
					<?php foreach ($this->intervalTypes as $key => $value): ?>
						<option value="<?= $key ?>"><?= $value ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="col-xs-6 np">
			<div class="col-xs-4 lh-35"><?= __('module_service_from') ?></div>	
			<div class="col-xs-2">
				<select name="from_day">
					<?php foreach ($this->days as $day) : ?>
						  <option value="<?= $day ?>"
								  ><?= $day ?></option>
						<?php endforeach; ?>
				</select>
			</div>
			<div class="col-xs-2">
				<select name="from_month">
					<?php foreach ($this->months as $month) : ?>
						  <option value="<?= $month ?>"
							<?= Helper_Default::getSelectedOrNull($this,'currentMonth',$month) ?>
								  ><?= $month ?></option>
						<?php endforeach; ?>
				</select>
			</div>

			<div class="col-xs-4">
				<select name="from_year">
					<?php foreach ($this->years as $year) : ?>
						  <option value="<?= $year ?>"
							<?= Helper_Default::getSelectedOrNull($this,'currentYear',$year) ?>
								  ><?= $year ?></option>
						<?php endforeach; ?>
				</select>
			</div>
			<div class="clearfix"></div>
			<div class="col-xs-4 mt-15 lh-35"><?= __('module_service_to') ?></div>
			<div class="col-xs-2 mt-15">
				<select name="to_day">
					<?php foreach ($this->days as $day) : ?>
						  <option value="<?= $day ?>"
								  ><?= $day ?></option>
						<?php endforeach; ?>
				</select>
			</div>
			<div class="col-xs-2 mt-15">
				<select name="to_month">
					<?php foreach ($this->months as $month) : ?>
						  <option value="<?= $month ?>"
							<?= Helper_Default::getSelectedOrNull($this,'currentMonth',$month) ?>
								  ><?= $month ?></option>
						<?php endforeach; ?>
				</select>
			</div>
			<div class="col-xs-4 mt-15">
				<select name="to_year">
					<?php foreach ($this->years as $year) : ?>
						  <option value="<?= $year ?>"
							<?= Helper_Default::getSelectedOrNull($this,'nextYear',$year) ?>
								  ><?= $year ?></option>
						<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="clearfix"></div>
		
		<?= __('module_service_icon') ?>
		<select name="icon">
			<?php foreach ($this->icons as $value): /* @var $value Article */ ?>
				<option value="<?= $value['name'] ?>"><?= $value['name'] ?></option>
			<?php endforeach; ?>
		</select>
		
		<div id="icon-box">
		<?php foreach ($this->icons as $value): /* @var $value Article */ ?>
		
			<div class="col-xs-4"><i class="fa fa-<?= $value['name'] ?>"></i> <?= $value['name'] ?> </div>
		
		<?php endforeach; ?> 
			<i class="fa fa-angle-down fa-3x icon-box-button"></i>
		</div>
		
		<br><?= __('module_service_article') ?>
		<select name="article_url_name">
			<?php foreach ($this->articles as $value): /* @var $value Article */ ?>
				<option value="<?= $value->url_name ?>"><?= $value->title.' ('.$value->perex.')' ?></option>
			<?php endforeach; ?>
		</select>
		
		<br><?= __('promo') ?>
		<select name="promo_url_name">
			<?php foreach ($this->articles as $value): /* @var $value Article */ ?>
				<option value="<?= $value->url_name ?>"><?= $value->title.' ('.$value->perex.')' ?></option>
			<?php endforeach; ?>
		</select>
		
			<br><?= __('module_service_conditions') ?>
		<select name="conditions_name">
			<?php foreach ($this->scannedDirectory as $value): /* @var $value  */ ?>
				<option value="<?= $value ?>"><?= $value ?></option>
			<?php endforeach; ?>
		</select>
		
		<div class="col-xs-9"></div>
		<div class="text-center col-xs-3 mt-15">
			<input type="submit" value="<?= __('save') ?>" class="btn">
		</div>
		<div class="clearfix"></div>
	</form>
</div>

<script>
	$('.icon-box-button').click(
				function(){
					
					if($(this).hasClass('fa-angle-down')){
						$('#icon-box').css({'height':'4650px'});
						$(this).removeClass('fa-angle-down').addClass('fa-angle-up');
					}else{
						$('#icon-box').css({'height':'58px'});
						$(this).removeClass('fa-angle-up').addClass('fa-angle-down');
					}
					
				}
			);

</script>