<?php
/**
 *  @author Jakub Pastuszek <pastuszek@itart.cz>
 *  @package modules/users
 */
class Module_Bootstrap_Users extends Art_Abstract_Module_Bootstrap {
	
	static function initialize()
	{
		Art_Event::on(Art_Event::LABEL_SETUP,function(){
			static::labelSetup();
		});
	}
	
	static function labelSetup() 
	{
		Art_Label::addLabelSet(array(
			'module_users_header'			=> 'Uživatelé',
			'module_users_companies_header'	=> 'Společnosti',
			'module_users_membership_from'	=> 'Členství od',
			'module_users_membership_to'	=> 'Členství do',
			'module_users_edit_user'		=> 'Úprava uživatele',
			'module_users_not_found'		=> 'Uživatel nenalezen',
			'module_users_edit_success'		=> 'Uživatel byl úspěšně upraven',
			'module_users_add_user'			=> 'Nový uživatel',
			'module_users_add_success'		=> 'Uživatel %s byl úspěšně přidán',
			'module_users_user_detail'		=> 'Detail uživatele',
			'module_users_personal_info'	=> 'Informace',
			'module_users_payments'			=> 'Platby',
			'module_users_manager'			=> 'Manažer',
			'module_users_add_service'		=> 'Přidat službu',
			'module_users_activate_service'	=> 'Aktivovat službu',
			'module_users_unmember_user'	=> 'Zbavit členství',
			'module_users_delete_user'		=> 'Odebrat uživatele',
			'module_users_authorize'		=> 'Schvalování uživatelů',
			'module_users_registered'		=> 'Registrován',
			'module_users_create_mail'		=> 'Vytvořit email',
			'module_users_new_mail'			=> 'Nový email',
			
			'module_registration_v_salutation_min'		=> 'Oslovení je příliš krátké',
			'module_registration_v_salutation_max'		=> 'Oslovení je příliš dlouhé',
			
			'module_users_v_change_password_wrong_actual'	=> 'Aktuální heslo není správné',
			'module_users_v_change_password_old_new_same'	=> 'Nové heslo musí být jiné než stávající',
			'module_users_v_change_password_not_same'	=> 'Nové hesla musejí být stejná',
			
			'module_users_v_password_new_min'		=> 'Nové heslo je příliš krátké',
			'module_users_v_password_new_max'		=> 'Nové heslo je příliš dlouhé',
			'module_users_v_code_note_max'			=> 'Poznámka je příliš dlouhá',
			
			'module_users_v_mail_subject_min'		=> 'Předmět je příliš krátký',
			'module_users_v_mail_subject_max'		=> 'Předmět je příliš dlouhý',
			'module_users_v_mail_body_min'			=> 'Tělo je příliš krátké',
			'module_users_v_mail_body_max'			=> 'Tělo je příliš dlouhé',
		
			'module_registration_v_membership_fee_min'	=> 'Hodnota členského poplatku je příliš nízká',
			'module_registration_v_membership_fee_not_integer'	=> 'Hodnota členského poplatku musí být číslo',
			
			'module_users_deposits'		=> 'Vklady',
			'module_users_interests'	=> 'Úrok v daném měsíci',
			
			'module_users_send_mail_none_user'		=> 'Nebyl vybrán žádný uživatel',
			'module_users_send_mail_success'		=> 'Email byl úspěšně odeslán',
			'module_users_resend_auth_email_success'=> 'Autorizační email byl znovu odeslán',
			'module_users_resend_reg_email_success'	=> 'Registrační email byl znovu odeslán',
			'module_users_unmember_success'			=> 'Uživatel byl úspěšně zbaven členství',
			'module_users_unmember_not_found'		=> 'Uživatel nebyl nalezen',
			'module_users_delete_contained_in_payments'=> 'Uživatel má přiřazené platby',
			'module_users_delete_contained_invited_users'=> 'Uživatel má pozvané uživatele',
			'module_users_delete_success'			=> 'Uživatel byl úspěšně vymazán',
			'module_users_delete_not_found'			=> 'Uživatel nebyl nalezen',
			'module_users_request_delete_success'	=> 'Žádost byla úspěšně vymazána',
			'module_users_request_delete_not_found'	=> 'Žádost nebyla nalezena',
			'module_users_authorize_success'		=> 'Uživatel byl úspěšně autorizován',
			'module_users_authorize_not_found'		=> 'Uživatel nebyl nalezen',
			'module_users_change_password_changed'	=> 'Heslo úspěšně změněno',
			'module_users_change_password_header'	=> 'Změna hesla',
			'module_users_change_password_actual'	=> 'Aktuální heslo',
			'module_users_change_password_new'		=> 'Nové heslo',
			'module_users_change_password_new_again'=> 'Opakuj nové heslo',
			'module_users_change_password_send'		=> 'Změnit heslo',
			'module_users_edit_header'				=> 'Změna údajů',
			'module_users_edit_change'				=> 'Potvrdit změnu',
			'module_users_count'					=> 'Počet členů',
			'module_users_new_invite_code_success'	=> 'Nový kod pro pozvánku úspěšně vytvořen',
			'module_users_new_invite_aborted'		=> 'Bylo dosaženo maximálního limitu kódů',
			'module_users_inviteted_by'				=> 'Registrovaný přes pozvání uživatele',
			'module_users_invite_code_created'		=> 'Vytvořené pozvánkové kody',
			'module_users_invite_code_users_joined'	=> 'Uživatelé, kteří se registrovali přes mé kódy',
			'module_users_generate_new_code'	=> 'Generování nového kódu',
			'module_users_inv_code_user'		=> 'Kód pro uživatele',
			'module_users_inv_code_note'		=> 'Poznámka ke kódu',
			'module_users_inv_code_current_codes'	=> 'Vygenerované kódy',
			'module_users_inv_code_generate_new'	=> 'Generovat',
			'module_users_authorize_firms'		=> 'Schvalování firem',
			'module_users_resend_auth_email'	=> 'Znovu zaslat autorizační email',
			'module_users_resend_reg_email'		=> 'Znovu zaslat registrační email',
			'module_users_membership_for_year'	=> 'Členství za rok',
			'module_users_send'					=> 'Odeslat',
			'module_users_manager_info'			=> 'Detail manažera',
			'module_users_service_detail'		=> 'Detail služby uživatele',
			'module_users_service_info'			=> 'Služba',
			'module_users_service_type'			=> 'Typ',
			'module_users_service_actual_price'	=> 'Aktuální cena',
			'module_users_service_time_interval'=> 'Časový interval',
			'module_users_last_logins'			=> 'Poslední přihlášení',
			'module_users_created_by'			=> 'Vytvořil',
			'module_users_code_owner'			=> 'Vlastník kódu',
			'module_users_invited_users'		=> 'Pozvaní uživatelé',
			'module_users_invited_by'			=> 'Pozvaný uživatelem',
			'module_users_complete_firm_registration_success'	=> 'Registrace firmy byla úspěšně dokončena',
			'module_users_complete_firm_registration_not_found'	=> 'Firma nebyla nalezena',
			'module_users_got_application'		=> 'Oznámit doručení přihlášky',
			'module_users_got_application_date'	=> 'Přihláška byla doručena dne: ',
			'module_users_not_got_application'	=> 'Oznámit nedoručení přihlášky',
			'module_users_not_got_application_date'	=> 'Oznámení o nedoručení přihlášky bylo odesláno dne: ',
			'module_users_reg_completed'		=> 'Registrace byla dokončena',
			'module_users_got_application_sent'	=> 'Zpráva o doručení přihlášky byla odeslána',
			'module_users_not_got_application_sent'	=> 'Zpráva o nedoručení přihlášky byla odeslána',
			'module_users_not_got_application_error'=> 'Nebyla nalezena přihláška, zpráva nebyla odeslána',
			'module_users_requests_header'		=> 'Žádosti o službu',
			'module_users_edit_salutation_success'=> 'Oslovení bylo úspěšně změněno',
			'module_users_delete_company'		=> 'Odebrat firmu',
			'module_users_edit_company'			=> 'Upravit firmu',
			'module_users_auth_person_info'		=> 'Info oprávněné osoby',
			'module_users_auth_person_address'	=> 'Adresa oprávněné osoby',
			'module_users_company_info'			=> 'Informace o firmě',
			'module_users_company_detail'		=> 'Detail firmy',
			'module_users_company_address'		=> 'Adresa firmy',
			'module_users_representant_person_info'	=> 'Info zástupce firmy',
			'module_users_representant_person_address'	=> 'Adresa zástupce firmy',
			'module_users_authorize_company_success'	=> 'Firma byla úspěšně autorizována',
			'module_users_authorize_company_not_found'	=> 'Firma nebyla nalezena',
			'module_users_change_manager'			=> 'Změnit manažera',
			'module_users_change_manager_header'	=> 'Změna manažera',
			'module_users_change_manager_success'	=> 'Uživateli byl úspěšně změněn manažer',
			'module_users_change_manager_not_found'	=> 'Uživatel nebyl nalezen',
			'module_users_representant_address'		=> 'Adresa zástupce společnosti',
			'module_users_set_data_header'			=> 'Vyplnění chybějících údajů',
			'module_users_remove_service_confirm'	=> 'Opravu chcete odebrat uživateli danou službu?',
			'module_users_managers'					=> 'Manažeři',
			
			'module_users_change_password_not_found'=> 'Uživatel nebyl nalezen',
			'module_users_delete_user_confirm'		=> 'Opravdu chcete smazat tohoto uživatele?',
			'module_users_request_delete_request_confirm'	=> 'Opravdu chcete smazat tuto žádost?',
			'module_users_request'					=> 'Žádost',
			'module_users_requests_send_email'		=> 'Odeslat emailovou zprávu',
			'module_users_resend_reg_email_error'	=> 'Při znovuodesílání registračního emailu nastala chyba',
			'module_users_unmember_user_confirm'	=> 'Opravdu chcete zbavit členství tohoto uživatele?',
			'module_users_spam_alert'				=> 'Opakovat odeslání zprávy je možné až po uplynutí %s minut',
			
			'module_users_edit_bank_account'		=> 'Nastavení čísla účtu',
			'bank_account_prefix'					=> 'Prefix čísla',
			'bank_account_basic'					=> 'Číslo',
			'bank_account_bank_code'				=> 'Kód banky',
			'module_users_bank_account_set'			=> 'Nastavit',
			'module_users_set_bank_account_set'		=> 'Číslo bankovního účtu bylo úspěšně nastaveno',
			
			'module_users_v_prefix_not_integer'		=> 'Prefix bankovního čísla musí být číslo',
			'module_users_v_basic_not_integer'		=> 'Bankovní číslo musí být číslo',
			'module_users_v_bank_code_not_integer'	=> 'Kód banky musí být číslo',
			'module_users_v_note_max'				=> 'Poznámka je příliš dlouhá',
			
			'module_users_remove_bank_account_success'	=> 'Bankovní číslo bylo úspěšně odstraněno',
			'module_users_remove_bank_account_not_found'=> 'Bankovní číslo nebylo nalezeno',
			'module_users_delete_bank_account_confirm'	=> 'Opravdu chcete smazat dané bankovní číslo?',
			));
	}
}			
