<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_dashboard_header') ?></h2>
	</div>
	<div class="col-sm-6 action-submenu page-actions">
		<div class="action-new tile">
			<a href="/<?= Art_Router::getLayer() ?>/dashboard/new">
			<?= icon('add'); ?>
			<?= __('add') ?></a>
		</div>
	</div>
</div>
	
<table class="table-default">
	<colgroup>
		<col class="w5">
		<col class="w25">
		<col class="w50">
		<col class="w20">
	</colgroup>
	<tr>
		<th class="text-center">!</th>
		<th><?= __('module_dashboard_content_header') ?></th>
		<th><?= __('module_dashboard_content_body') ?></th>
		<th><?= __('module_dashboard_content_date') ?></th>
	</tr>
	<?php foreach (array_reverse($this->dashboard) as $post) : /* @var $post Dashboard */ ?>
	<tr>
		<td class="text-center">
			<?php if ($post->important) : ?>
				<i title="<?= __('module_dashboard_important') ?>" class="fa fa-exclamation"></i>
			<?php endif; ?>
		</td>
		<td><?= $post->header ?></td>
		<td>
			<a href="<?= $post->a_detail ?>"><?= Art_Filter::cutString($post->body,200) ?></a>
		</td>
		<td>
			<?= nice_date($post->created_date) ?>
			<div class="inline-actions">
				<a href="<?= $post->a_edit ?>"><i class="fa fa-pencil"></i></a>
				<button <?= $this->delete_single_request->getHTML(array('id'=>$post->id)) ?> title="<?= __('delete') ?>"><i class="fa fa-trash-o"></i></button>
			</div>
		</td>
	</tr>
	<?php endforeach; ?>
</table>