<h2><?= __('module_emailtemplate_edit_emailtemplate') ?></h2>

<form <?= $this->request->getHTML() ?>>
	<div class="background-white pa-15">
		<table class="table-default email-templates">
			<tr>
				<td>
					<label><?= __('module_emailtemplate_name') ?></label>
					<input type="text" disabled="disabled" name="name" placeholder="<?= __('module_emailtemplate_name') ?>" value="<?= $this->emailtemplate->name ?>">
				</td>
				<td>
					<label for="email-subject"><?= __('module_emailtemplate_subject') ?></label>
					<input id="email-subject" type="text" name="subject" placeholder="<?= __('module_emailtemplate_subject') ?>" value="<?= $this->emailtemplate->subject ?>">
				</td>
			</tr>
			<tr>
				<td>
					<label for="email-from"><?= __('module_emailtemplate_from_name') ?></label>
					<input id="email-from" type="text" name="from_name" placeholder="<?= __('module_emailtemplate_from_name') ?>" value="<?= $this->emailtemplate->from_name ?>">
				</td>
				<td>
					<label for="email-from"><?= __('module_emailtemplate_from_email') ?></label>
					<input i="email-from" type="text" name="from_email" placeholder="<?= __('module_emailtemplate_from_email') ?>" value="<?= $this->emailtemplate->from_email ?>">
				</td>
			</tr>
			<tr>
				<td>
					<label for="email-to"><?= __('module_emailtemplate_reply_to_name') ?></label>
					<input id="email-to" type="text" name="reply_to_name" placeholder="<?= __('module_emailtemplate_reply_to_name') ?>" value="<?= $this->emailtemplate->reply_to_name ?>">
				</td>
				<td>
					<label for="email-reply-to"><?= __('module_emailtemplate_reply_to_email') ?></label>
					<input id="email-reply-to" type="text" name="reply_to_email" placeholder="<?= __('module_emailtemplate_reply_to_email') ?>" value="<?= $this->emailtemplate->reply_to_email ?>">
				</td>
			</tr>
		</table>
		<div class="ml-15 mt-15 mr-10 mb-15">
			<label for="email-body"><?= __('module_emailtemplate_body') ?></label>
			<textarea id="email-body" class="ckeditor" rows="8" name="body" placeholder="<?= __('module_emailtemplate_body') ?>"><?= $this->emailtemplate->body ?></textarea>
		</div>
	</div>
	<div class="save-view-buttons mt-15">
		<input type="submit" value="<?= __('save') ?>" class="button">
	</div>
</form>