<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_emailtemplate') ?></h2>
	</div>
	<div class="col-sm-6 action-submenu page-actions">
		<div class="action-new tile">
			<a href="/<?= Art_Router::getLayer() ?>/emailtemplate/new">
			<?= icon('add'); ?>
			<?= __('module_emailtemplate_add') ?></a>
		</div>
	</div>
</div>

<table class="table-default">
	<colgroup>
		<col class="w25">
	</colgroup>
	<tr>
		<th class="text-center">Název</th>
		<th>Předmět</th>
	</tr>
	<?php foreach($this->emailtemplates AS $emailtemplate): ?>
		<?php $href = '/' . Art_Router::getLayer() . '/emailtemplate/edit/' . $emailtemplate->id; ?>
		<tr>
			<td class="text-left">
				<a href="<?= $href ?>"><?= $emailtemplate->name ?></a>
			</td>
			<td class="text-left">
				<a href="<?= $href ?>"><?= $emailtemplate->subject ?></a>
				<div class="inline-actions">
					<a href="<?= $href ?>"><i class="fa fa-pencil edit"></i></a>
					<button <?= $this->delete_single_request->getHTML(array('id' => $emailtemplate->id, 'name' => $emailtemplate->guid)) ?> title="<?= __('delete') ?>"><i class="fa fa-trash-o"></i></button>
				</div>
			</td>
		</tr>
	<?php endforeach; ?>
</table>