<h2><?= __('module_default_value_edit') ?></h2>

<form <?= $this->request->getHTML() ?>>
	<table class="table-default">
		<colgroup>
			<col class="w20">
			<col>
		</colgroup>
		<tr>
			<td class="xsmall-td text-right">
				<?= __('module_default_value_name') ?>
			</td>
			<td>
				<input type="text" name="name" value="<?= $this->item->name ?>" disabled="disabled">
			</td>
		</tr>
		<tr>
			<td class="xsmall-td text-right">
				<?= __('module_default_value_type') ?>
			</td>
			<td>
				<input type="text" name="type" value="<?= $this->item->type ?>" disabled="disabled">
			</td>
		</tr>
		<tr>
			<td class="text-right">
				<?= __('module_default_value_value') ?>
			</td>
			<td>
				<?php if( $this->item->type === Art_Model_Default_Value::TYPE_HTML): ?>
					<textarea class="ckeditor" rows="8" name="value" placeholder="<?= __('module_default_value_value') ?>"><?= $this->item->value ?></textarea>
				<?php else: ?>
					<input type="text" name="value" placeholder="<?= __('module_default_value_value') ?>" autofocus="true" value="<?= $this->item->value ?>">
				<?php endif; ?>
			</td>
		</tr>
	</table>
	<div class="save-view-buttons mt-15">
		<input type="submit" value="<?= __('save') ?>" class="button">
	</div>
</form>