<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_default_value') ?></h2>
	</div>
	<div class="col-sm-6 action-submenu">
		<div class="action-new">
			<a href="/<?= Art_Router::getLayer() ?>/default_value/new">
			<i class="fa fa-plus fa-2x"></i>
			<?= __('add') ?></a>
		</div>
	</div>
</div>
	
<table class="table-default">
	<tr>
		<th><?= __('module_default_value_name') ?></th>
		<th><?= __('note') ?></th>
		<th><?= __('module_default_value_type') ?></th>
		<th><?= __('module_default_value_value') ?></th>
		<th></th>
	</tr>
	<?php foreach($this->items as $item): ?>
		<tr>
			<td>
				<a href="<?= '/'.Art_Router::getLayer().'/default_value/edit/'.$item->id ?>"><?= Art_Filter::cutString($item->name,40) ?></a>
			</td>
			<td><?= $item->note ?></td>
			<td><?= $this->types[$item->type] ?></td>
			<td><?= Art_Filter::cutString($item->value, 100) ?></td>
			<td>
				<div class="inline-actions">
					<a href="<?= '/'.Art_Router::getLayer().'/default_value/edit/'.$item->id ?>"><i class="fa fa-pencil"></i></a>
				</div>
			</td>
		</tr>
	<?php endforeach; ?>
</table>