<h2><?= __('module_default_value_add') ?></h2>

<form <?= $this->request->getHTML() ?>>
	<table class="table-default">
		<tr>
			<td class="xsmall-td text-right">
				<?= __('module_default_value_name') ?>
			</td>
			<td>
				<input type="text" name="name" placeholder="<?= __('module_default_value_name') ?>">
			</td>
		</tr>
		<tr>
			<td class="xsmall-td text-right">
				<?= __('note') ?>
			</td>
			<td>
				<input type="text" name="note" placeholder="<?= __('note') ?>">
			</td>
		</tr>
		<tr>
			<td class="xsmall-td text-right">
				<?= __('module_default_value_type') ?>
			</td>
			<td>
				<select name="type" id="module_default_value_type_selector">
					<?php foreach($this->types AS $key => $type) :?>
					<option value="<?= $key ?>"><?= $type ?></option>
					<?php endforeach; ?>
				</select>
			</td>
		</tr>
		<tr>
			<td>
				<?= __('module_default_value_value') ?>
			</td>
			<td>
				<input type="text" name="value_text" id="module_default_value_value_input" placeholder="<?= __('module_default_value_value') ?>">
				<span id="module_default_value_value_textarea">
					<textarea class="ckeditor" rows="8" name="value_html" placeholder="<?= __('module_default_value_value') ?>"></textarea>
				</span>
			</td>
		</tr>
	</table>
	<div class="text-center">
		<input type="submit" value="<?= __('save') ?>" class="button-save">
	</div>
</form>

<script type="text/javascript">
$(function(){
	var $typeSelector = $("#module_default_value_type_selector");
	var $input = $("#module_default_value_value_input");
	var $textarea = $("#module_default_value_value_textarea");
		
	$typeSelector.change(function(){		
		if($typeSelector.val() === 'html')
		{
			$input.hide();
			$textarea.show();
		}
		else
		{
			$input.show();
			$textarea.hide();
		}
	});
	
	$textarea.hide();
});
</script>