<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
<head>
	<meta charset="UTF-8">
	<?= Art_Template::renderMeta() ?>
	<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link rel="icon" href="/favicon.png">
	<?= Art_Template::loadExtensions(array('jquery', 'bootstrap', 'font-awesome', 'chart')) ?>
	<?= Art_Template::renderCSS(array( 'system.less', 'style.less' )); ?>
	<?= Art_Template::renderJS(); ?>
</head>
<body>
	<div id="club_header">
		<a href="<?= DEFAULT_DOMAIN ?>">TBdevelopment.cz</a>
	</div>
	<div class="body">
		<div class="box">
			<div class="col-md-7 login-box">
				<div class="col-md-5 register">
					<div class="body">
						<div class="box">
							<h3>Spolek přátel při TBDI</h3>
							<p>
								Spolek přátel při TBDI je partnerským klubem společnosti TB development&investment s&nbsp;kterou úzce spolupracuje na rozvoji společnosti a podílí se prostřednictvím svých členů na obchodních aktivitách.
							</p><p>
								Klub je sdružením lidí, kteří se rozhodli změnit své zvyky a s naší pomocí snížit své náklady či zhodnotit finanční úspory. 
							</p>
							<p><i class="fa fa-facebook-official fa-2x"></i> <a href="https://www.facebook.com/Spolek-p%C5%99%C3%A1tel-p%C5%99i-TBDI-1140868825942449" target="_blank" class="a-fb-link">Spolek přátel při TBDI na FB</a></p>
							<a href="/registration"><i class="fa fa-angle-right"></i> Stát se členem</a>
						</div>
					</div>
				</div>
				<div class="col-md-7 login">
					<div class="body">
						<div class="box">
							
							<?= Art_Template::renderContent() ?>
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
	$('.pass-input').focus(function(){
		$('.fa-lock').addClass('fa-unlock-alt').removeClass('fa-lock');
	});
	$('.pass-input').focusout(function(){
		$('.fa-unlock-alt').addClass('fa-lock').removeClass('fa-unlock-alt');
	});
</script>
</body>

</html>



