<h3><?= __('module_registration_header') ?></h3>
<div class="linka-clenem"></div>
<div class="col-sm-6 col-sm-pull-1">
	<a href="/registration/legalperson" class="registration_button"><?= __('legal_person') ?></a>	
</div>
<div class="col-sm-6">
<a href="/registration/naturalperson" class="registration_button"><?= __('natural_person') ?></a>
</div>
<div class="col-xs-11 mt-20"><a href="/">Návrat na přihlášení</a> </div>