<!DOCTYPE html>
<?php /**
 * <nav>
					<a href="/" class="selected">Home</a>
					<a href="<?= '/registration' ?>">Registrace</a>
					<a href="<?= '/forgotten' ?>">Zapomenuté heslo</a>
					<a href="<?= '/cabinet' ?>">Cabinet</a>
				</nav>
 */

?>
<html prefix="og: http://ogp.me/ns#">
<head>
	<meta charset="UTF-8">
	<?= Art_Template::renderMeta() ?>
	<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link rel="icon" href="/favicon.png">
	<?= Art_Template::loadExtensions(array( 'bootstrap' )) ?>
	<?= Art_Template::renderCSS(array( 'system.less', 'style.less' )); ?>
	<?= Art_Template::renderJS(); ?>
</head>
<body>
	<div class="body">
		<div class="box">
			<div class="col-md-7 login-box clenem">
				<div class="col-md-12">
					<div class="body">
						<div class="box text-center">
							<?= Art_Template::renderContent() ?>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<?php /**
	<div id="cookie-policy">
		<p>Soubory cookie nám pomáhají poskytovat a zlepšovat služby tohoto webu.
		<a href="#">Více informací</a><button>Souhlasím</button>
		</p>
	</div>
	 */ ?>
	<script>
	$('.pass-input').focus(function(){
		$('.fa-lock').addClass('fa-unlock-alt').removeClass('fa-lock');
	});
	$('.pass-input').focusout(function(){
		$('.fa-unlock-alt').addClass('fa-lock').removeClass('fa-unlock-alt');
	});
</script>
</body>
</html>


</body>
</html>
