<h2><?= __('module_label_new_label') ?></h2>

<form <?= $this->request->getHTML() ?>>	
	<input type="text" name="key" placeholder="<?= __('module_label_key') ?>">
	<input type="text" name="group" placeholder="<?= __('module_label_group') ?>">

	<?php foreach($this->languages AS $language): ?>
		<input type="text" name="<?= $language ?>" placeholder="<?= __('module_label_'.$language) ?>">
	<?php endforeach; ?>
	
	<input type="submit" value="<?= __('save') ?>">
</form>