<h2><?= __('module_meta_edit_meta') ?></h2>

<form <?= $this->request->getHTML() ?>>
	<table class="table-default key-value-list">
		<colgroup>
			<col class="w20">
			<col>
		</colgroup>
		<tr>
			<td class="text-right">
				<?= __('key') ?>
			</td>
			<td>
				<input type="text" name="key" placeholder="<?= __('module_meta_key') ?>" value="<?= $this->meta->key ?>" disabled>
			</td>
		</tr>
		<tr>
			<td class="text-right">
				<?= __('content') ?>
			</td>
			<td>
				<input type="text" name="content_cs" autofocus placeholder="<?= __('module_meta_content_cs') ?>" value="<?= $this->meta->content_cs ?>">
			</td>
		</tr>
		<!-- <tr>
			<td class="text-right">
				<?= __('module_meta_default') ?>
			</td>
			<td>
				<?= $this->default ?>
			</td>
		</tr> -->
	</table>
	<div class="save-view-buttons mt-15">
		<input type="submit" value="<?= __('save') ?>" class="button">
	</div>
</form>