<h2><?= __('module_meta_edit_meta') ?></h2>

<form <?= $this->request->getHTML() ?>>
	<table class="table-default">
		<tr>
			<td class="xsmall-td text-right">
				<?= __('key') ?>
			</td>
			<td>
				<input type="text" name="key" placeholder="<?= __('module_meta_key') ?>" value="<?= $this->meta->key ?>" disabled="disabled">
			</td>
		</tr>
		<tr>
			<td>
				<?= __('content') ?>
			</td>
			<td>
				<input type="text" name="content_cs" placeholder="<?= __('module_meta_content_cs') ?>" value="<?= $this->meta->content_cs ?>">
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<?= __('module_meta_default').': '.$this->default ?>
			</td>
		</tr>
	</table>
	<div class="text-center">
		<input type="submit" value="<?= __('save') ?>" class="button-save">
	</div>
</form>