<form>
	<div class="row">
		<div class="col-sm-6 action-name">
			<h2><?= __('module_meta_metas') ?></h2>
		</div>
		<div class="col-sm-6 action-submenu page-actions">
			<div class="action-new tile">
				<a href="/<?= Art_Router::getLayer() ?>/meta/new">
				<?= icon('add') ?>
				<?= __('add') ?></a>
			</div>
			<button class="action-delete tile" <?= $this->delete_request->getHTML() ?>>
				<?= icon('add') ?>
				<?= __('delete') ?>
			</button>
		</div>
	</div>
		
	<table class="table-default">
		<colgroup>
			<col class="f35">
			<col class="w30">
			<col class="w60">
		</colgroup>
		<tr>
			<th class="text-center">
				<input type="checkbox" onclick="toggleCheck(this,'.module_meta_index .cb-meta-list')">
			</th>
			<th>
				<?= __('module_meta_key') ?>
			</th>
			<th>
				<?= __('module_meta_content_cs') ?>
			</th>
		</tr>
		<?php foreach($this->metas as $meta) : ?>
			<tr>
				<td class="text-center">
					<input type="checkbox" name="meta_<?= $meta->id ?>" class="cb-meta-list">
				</td>
				<td>
					<a href="<?= '/'.Art_Router::getLayer().'/meta/edit/'.$meta->id ?>"><?= $meta->key ?></a>
				</td>
				<td>
					<?= $meta->content_cs ?>
					<div class="inline-actions">
						<a href="<?= '/'.Art_Router::getLayer().'/meta/edit/'.$meta->id ?>"><i class="fa fa-pencil"></i></a>
					</div>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</form>	