<form>
<div class="row">
	<div class="col-sm-6 action-name">
		<h2><?= __('module_meta_metas') ?></h2>
	</div>
	<div class="col-sm-6 action-submenu">
		<button class="action-delete" <?= $this->delete_request->getHTML() ?>>
			<i class="fa fa-trash-o fa-2x"></i>
			<?= __('delete') ?>
		</button>
		<div class="action-new">
			<a href="/<?= Art_Router::getLayer() ?>/meta/new">
			<i class="fa fa-plus fa-2x"></i>
			<?= __('add') ?></a>
		</div>
	</div>
</div>
	<div class="clear"></div>


	
<table class="table-default">
	<tr>
		<th class="text-center"><input type="checkbox" onclick="toggleCheck(this,'.module_meta_index .cb-meta-list')"></th>
		<th class="text-center"><?= __('module_meta_key') ?></th>
		<th><?= __('module_meta_content_cs') ?></th>
		<th></th>
	</tr>
	<?php foreach($this->metas AS $meta): ?>
		<tr>
			<td class="text-center"><input type="checkbox" name="meta_<?= $meta->id ?>" class="cb-meta-list"></td>
			<td class="text-center"><?= Art_Filter::cutString($meta->key,40) ?></td>
			<td><?= Art_Filter::cutString($meta->content_cs,100) ?></td>
			<td class="text-center"><a href="<?= '/'.Art_Router::getLayer().'/meta/edit/'.$meta->id ?>"><i class="fa fa-pencil edit"></i></a></td>
		</tr>
	<?php endforeach; ?>
</table>
</form>	