<h2><?= __('module_meta_new_meta') ?></h2>

<form <?= $this->request->getHTML() ?>>
	<table class="table-default key-value-list">
		<colgroup>
			<col class="w20">
			<col>
		</colgroup>
		<tr>
			<td class="text-right">
				<?= __('key') ?>
			</td>
			<td>
				<input type="text" name="key" autofocus>
			</td>
		</tr>
		<tr>
			<td class="text-right">
				<?= __('value') ?>
			</td>
			<td>
				<input type="text" name="content_cs">
			</td>
		</tr>
	</table>
	<div class="save-view-buttons mt-15">
		<input type="submit" value="<?= __('save') ?>" class="button">
	</div>
</form>