<h3><?= __('module_filter_quick_header') ?></h3>

<form method="post" class="form">
	<div class="filter payments">
		<div>
			<label for="payer-name"><?= __('module_payments_payer') ?></label>
			<input 	id="payer-name" name="payer-name" type="text" class="form-control" placeholder="<?= __('module_payments_payer') ?>"
					value="<?= Helper_Default::getPropertyOrNull($this->data, 'name') ?>">
		</div>
	</div>
</form>